package com.example.hebrewphrases;

import android.content.Context;
import android.content.SharedPreferences;

import com.example.common.CommonDataManager;
import com.example.common.Phrase;

import java.util.ArrayList;

public class HebrewDataManager extends CommonDataManager {

    ArrayList<Phrase> phrases;

    public HebrewDataManager() {
        phrases = new ArrayList<>();

        phrases.add(new Phrase("אבד עליו הכלח ", " התיישן, עבר זמנו, אנכרוניסטי."));
        phrases.add(new Phrase("אבדון ", " חורבן, כליה, כליון, הרס גמור."));
        phrases.add(new Phrase("אבוס ", " כלי לנתינת אוכל לבהמות."));
        phrases.add(new Phrase("אבוקה ", " לפיד, משואה."));
        phrases.add(new Phrase("אבחה ", " 1. תנופה; 2. טבח, חורבן."));
        phrases.add(new Phrase("אבטיפוס ", " מקור."));
        phrases.add(new Phrase("אבן הראשה ", " האבן האמצעית בקשת בניין."));
        phrases.add(new Phrase("אבן יסוד ", " מרכיב חיוני, עליו מבוסס דבר מה."));
        phrases.add(new Phrase("אבן נגולה מעל ליבו ", " הוקל לו, רווח לו."));
        phrases.add(new Phrase("אבן נגף ", " מכשול, תקלה, מהמורה, פח."));
        phrases.add(new Phrase("אבן פינה ", " עיקר."));
        phrases.add(new Phrase("אבן ריחיים ", " עול כבד."));
        phrases.add(new Phrase("אבן שואבת ", " דבר שהוא מוקד התעניינות."));
        phrases.add(new Phrase("אבן שפה ", " האבנים שבשולי הכביש, תחילת המדרכה."));
        phrases.add(new Phrase("אבניים ", " גלגל ליצירת כלי חרס."));
        phrases.add(new Phrase("אבסולוטי ", " מוחלט."));
        phrases.add(new Phrase("אבק אדם ", " אדם נטול ערך."));
        phrases.add(new Phrase("אבק פורח ", " דבר נטול כל ערך."));
        phrases.add(new Phrase("אברך ", " איש צעיר, נשוי בשנותיו הראשונות."));
        phrases.add(new Phrase("אגב ", " בהזדמנות זו, תוך כדי כך, אגב אורחא."));
        phrases.add(new Phrase("אגד ", " חבילה, צרור, אמתחת, ציקלון."));
        phrases.add(new Phrase("אגוז קשה לפיצוח ", " בעיה שקשה לפתור אותה."));
        phrases.add(new Phrase("אגליטרי ", " שוויוני."));
        phrases.add(new Phrase("אגן ", " ספל, קערה, בזיך, קובעת."));
        phrases.add(new Phrase("אגרונום ", " מומחה בתחום החקלאות."));
        phrases.add(new Phrase("אגרסיבי ", " תוקפני."));
        phrases.add(new Phrase("אד הוק ", " ייעודי, במיוחד לשם תכלית מסוימת."));
        phrases.add(new Phrase("אדווה ", " גל קטן."));
        phrases.add(new Phrase("אדם מן הישוב ", " אדם מתורבת."));
        phrases.add(new Phrase("אדמת טרשים ", " אדמה סלעית, שאינה ניתנת לעיבוד."));
        phrases.add(new Phrase("אדמת שלחין ", " קרקע חקלאית בהשקיה מלאכותית."));
        phrases.add(new Phrase("אדן ", " בסיס, יסוד  צירוף מוכר: אדן החלון ."));
        phrases.add(new Phrase("אדנות ", " שלטון, שררה, עצר, מרות."));
        phrases.add(new Phrase("אדרבה ואדרבה ", " ההפך הוא הנכון."));
        phrases.add(new Phrase("אהבה התלויה בדבר ", " אהבה מתוך מניעים אישיים."));
        phrases.add(new Phrase("אהדדי ", " באופן הדדי, זה לזה."));
        phrases.add(new Phrase("אוב ", " 1. כלי עור לנוזלים, נאד, חמת; 2. סיאנס, כישוף."));
        phrases.add(new Phrase("אובד עצות ", " מבולבל, נבוך, איבד את העשתונות."));
        phrases.add(new Phrase("אובייקט ", " עצם."));
        phrases.add(new Phrase("אובייקטיבי ", " ענייני, חסר העדפה אישית."));
        phrases.add(new Phrase("אובליגטורי ", " מחייב."));
        phrases.add(new Phrase("אוגדן ", " קלסר."));
        phrases.add(new Phrase("אוד ", " גזיר עץ בוער, שלא נשרף כולו."));
        phrases.add(new Phrase("אוד מוצל מאש ", " שריד, פליט."));
        phrases.add(new Phrase("אוד עשן ", " כינוי לאדם תשוש."));
        phrases.add(new Phrase("אווילות ", " טיפשות."));
        phrases.add(new Phrase("אוונגרדי ", " חדשני."));
        phrases.add(new Phrase("אוזלת יד ", " חוסר יכולת, אימפוטנציה, קוצר יד."));
        phrases.add(new Phrase("אוזניים לכותל ", " מצב שקשה לשמור בו סוד."));
        phrases.add(new Phrase("אוטוביוגרפיה ", " תולדות האדם, אותן כתב בעצמו."));
        phrases.add(new Phrase("אוטודידקט ", " לומד בעצמו."));
        phrases.add(new Phrase("אוטוקרט ", " שליט יחיד, טירן, דספוט, דיקטטור."));
        phrases.add(new Phrase("אויל ", " טיפש, סכל, שוטה, כסיל."));
        phrases.add(new Phrase("אומדן ", " הערכה, שומה."));
        phrases.add(new Phrase("אומניפוטנט ", " כל-יכול."));
        phrases.add(new Phrase("אומר דרשני ", " דורש עיון."));
        phrases.add(new Phrase("און ", " כוח, גבורה, איל, עזוז, מעוז."));
        phrases.add(new Phrase("אונגרד ", " חלוץ, חדשני."));
        phrases.add(new Phrase("אוניברסלי ", " עולמי, כללי."));
        phrases.add(new Phrase("אוניפורמי ", " בעל צורה אחידה."));
        phrases.add(new Phrase("אונקיה ", " מידת משקל קטנה."));
        phrases.add(new Phrase("אופורטוניזם ", " סתגלנות, פשרנות אידיאולוגית."));
        phrases.add(new Phrase("אופורטוניסט ", " מנצל הזדמנויות."));
        phrases.add(new Phrase("אופטימלי ", " מיטבי, הטוב ביותר."));
        phrases.add(new Phrase("אופן ", " גלגל."));
        phrases.add(new Phrase("אוצר ", " מי שממונה על המצגים במוזיאון."));
        phrases.add(new Phrase("אוצר בלום ", " 1. אוצר גדול; 2. אדם בעל ידיעות רחבות."));
        phrases.add(new Phrase("אורבני ", " עירוני."));
        phrases.add(new Phrase("אור יקרות ", " אור נעים."));
        phrases.add(new Phrase("אורגניזם ", " יצור חי."));
        phrases.add(new Phrase("אורו עיניו ", " אורו פניו, שמח, התמלא חיים."));
        phrases.add(new Phrase("אורחה ", " שיירה  המצויה בדרך ."));
        phrases.add(new Phrase("אורחו וריבעו ", " דרך חייו, מנהגיו."));
        phrases.add(new Phrase("אורך רוח ", " סבלנות."));
        phrases.add(new Phrase("אורלוגין ", " שעון קיר."));
        phrases.add(new Phrase("77) אורקל ", " מגיד עתידות."));
        phrases.add(new Phrase("אורתודוכסי ", " 1. שמרן, פוריט 2. אדוק בדתו."));
        phrases.add(new Phrase("אושיה ", " 1. איש ציבור, ידוען; 2. משען, יסוד  נכתב גם “אשיה” "));
        phrases.add(new Phrase("אותה הגברת בשינוי אדרת ", " אותו הדבר, שינוי חיצוני לא מהותי."));
        phrases.add(new Phrase("אותיות פורחות ", " דיבור שאינו ברור."));
        phrases.add(new Phrase("אות קין ", " בושה שאין למחותה, אות קלון."));
        phrases.add(new Phrase("אותיות של טל ומטר ", " אותיות קטנות מאוד."));
        phrases.add(new Phrase("אותיות של קידוש לבנה ", " אותיות גדולות מאוד."));
        phrases.add(new Phrase("אותנטי ", " אמיתי, מקורי, לא מזויף."));
        phrases.add(new Phrase("אזוב ", " כינוי לטחב המכסה אבנים ועצים."));
        phrases.add(new Phrase("אזוטרי ", " ידוע למעטים, סודי."));
        phrases.add(new Phrase("אזניו כרויות ", " אוזניו פתוחות, הוא מקשיב היטב."));
        phrases.add(new Phrase("אזניים לכותל ", " המקום או המצב אינם מתאימים לחשוף בהם סוד."));
        phrases.add(new Phrase("אזר חלציו ", " התחזק, אזר כוח, שינס מותניו."));
        phrases.add(new Phrase("אח ", " תנור, קמין, כירה, כבשן."));
        phrases.add(new Phrase("אחד בפה ואחד בלב ", " צביעות, אין פיו ולבו שווים."));
        phrases.add(new Phrase("אחו ", " כר דשא, שדה מרעה, אפר."));
        phrases.add(new Phrase("אחוז תזזית ", " משוגע."));
        phrases.add(new Phrase("אחז את החבל בשני קצותיו ", " ביצע שני דברים מנוגדים."));
        phrases.add(new Phrase("אחז את השור בקרניו ", " נכנס ללב העניין, נכנס בעובי הקורה."));
        phrases.add(new Phrase("אחז בקרנות המזבח ", " תפס מחסה, ביקש מפלט."));
        phrases.add(new Phrase("אחיזת עיניים ", " תרמית, הולכת שולל."));
        phrases.add(new Phrase("אחר רוחו ", " כפי שרצה."));
        phrases.add(new Phrase("אחרי המבול ", " לא אכפת לי."));
        phrases.add(new Phrase("אחרית ", " סוף, קץ."));
        phrases.add(new Phrase("אחריתו עדי עובד ", " סופו רע ומר."));
        phrases.add(new Phrase("אטב ", " מהדק נייר או כביסה לחבל."));
        phrases.add(new Phrase("אטרופיה ", " התנוונות."));
        phrases.add(new Phrase("איבד את העשתונות ", " התבלבל, נבוך, אובד עצות."));
        phrases.add(new Phrase("איד ", " צרה, אסון, שבר, פיד."));
        phrases.add(new Phrase("אידיליה ", " שלווה, הרמוניה, פסטורליה."));
        phrases.add(new Phrase("אידרה ", " עצם של דג."));
        phrases.add(new Phrase("איוולת ", " שטות."));
        phrases.add(new Phrase("איוושה ", " רחש קל."));
        phrases.add(new Phrase("איחוי ", " חיבור, תפירה."));
        phrases.add(new Phrase("איטר ", " שמאלי."));
        phrases.add(new Phrase("איכה? ", " איך? הכיצד?"));
        phrases.add(new Phrase("איכול ", " בעירה, שריפה."));
        phrases.add(new Phrase("איל ", " כוח, תעצומה, גבורה, עוז, חוסן, חיל."));
        phrases.add(new Phrase("אילוח ", " זיהום, אינפקציה."));
        phrases.add(new Phrase("אילולא ", " אם לא, אילו לא, לולא, אלמלא."));
        phrases.add(new Phrase("אילוסטרציה ", " 1. איור; 2. הדגמה, המחשה."));
        phrases.add(new Phrase("אילני סרק קולם הולך ", " טיפש המרבה להתרברב."));
        phrases.add(new Phrase("אלפס ", " סיר, מרחשת, קלחת, קדרה, פרור."));
        phrases.add(new Phrase("אימום ", " תבנית של כף הרגל."));
        phrases.add(new Phrase("אימפולסיבי ", " מונע על-ידי דחפים."));
        phrases.add(new Phrase("אימפרוביזציה ", " אלתור."));
        phrases.add(new Phrase("אימץ את ידיו ", " עודד אותו, דרבן אותו."));
        phrases.add(new Phrase("אימרה ", " 1. פתגם, מטבע לשון, מימרה ;2. שולי האריג."));
        phrases.add(new Phrase("אימתי ", " מתי."));
        phrases.add(new Phrase("אין אונים ", " חוסר יכולת, אוזלת יד, קוצר יד."));
        phrases.add(new Phrase("אין את נפשו ", " אינו רוצה."));
        phrases.add(new Phrase("אין בלבו עליו ", " אינו כועס עליו."));
        phrases.add(new Phrase("אין הנחתום מעיד על עיסתו ", "אדם לא יכול לחוות דעה על מעשיו שלו."));
        phrases.add(new Phrase("אין הריחיים בצווארו ", " אין לו בעיות פרנסה."));
        phrases.add(new Phrase("אין כוחו אלא בפיו ", " פטפטן, שמבטיח רבות ואינו מקיים."));
        phrases.add(new Phrase("אין לו אח ורע ", " אין כמותו."));
        phrases.add(new Phrase("אין לו דמים ", " יקר ערך."));
        phrases.add(new Phrase("אין לו חלק ונחלה ", " אין לו קשר."));
        phrases.add(new Phrase("אין לו חקר ", " לא ניתן להערכה."));
        phrases.add(new Phrase("אין לו שחר ", " לא מבוסס."));
        phrases.add(new Phrase("אין מנוס ", " אין ברירה."));
        phrases.add(new Phrase("אין נביא בעירו ", " אדם אינו זוכה להערכה בסביבתו."));
        phrases.add(new Phrase("אין סכין מתחדדת אלא בירך חברתה ", " לימוד בצוותא משפר את הלמידה."));
        phrases.add(new Phrase("אין סתרו כגילויו ", " צבוע, אין פיו ולבו שווים."));
        phrases.add(new Phrase("אין עליו עוררין ", " אין התנגדות,, התפרץ לדלת פתוחה, לית מאן דפליג."));
        phrases.add(new Phrase("אין עשן בלא אש ", " אין דבר ללא סיבה."));
        phrases.add(new Phrase("אין פיו ולבו שווים ", " צבוע, אין סתרו כגילויו."));
        phrases.add(new Phrase("אין תוכו כברו ", " צבוע, אחד בפה ואחד בלב."));
        phrases.add(new Phrase("אינדוקציה ", " לימוד מהפרט אל הכלל."));
        phrases.add(new Phrase("אינדיקטור ", " מדד, אבן בוחן, אמת מידה."));
        phrases.add(new Phrase("אינהרנטי ", " פנימי, טבוע."));
        phrases.add(new Phrase("אינטגרלי ", " כולל, שלם."));
        phrases.add(new Phrase("אינטראקציה ", " יחסי גומלין."));
        phrases.add(new Phrase("אינטרוברטי ", " מופנם."));
        phrases.add(new Phrase("אינספירציה ", " השראה."));
        phrases.add(new Phrase("אינפנטילי ", " ילדותי."));
        phrases.add(new Phrase("אינקוגניטו ", " בעילום שם, אנונימי, אלמוני."));
        phrases.add(new Phrase("אינרציה ", " 1. שגרה; 2. התמדה."));
        phrases.add(new Phrase("איסטניס ", " אנין, מעודן, יפה נפש."));
        phrases.add(new Phrase("איסתרא בלגינא קיש קיש קריא ", "טיפש המרבה להתרברב, אילני סרק קולם הולך."));
        phrases.add(new Phrase("איפה ", " מידה עתיקה."));
        phrases.add(new Phrase("איפה ואיפה ", " אפליה, משוא פנים."));
        phrases.add(new Phrase("איפול", "הטלת סודיות."));
        phrases.add(new Phrase("איפכא מסתברא ", " להפך, ההפך הוא הנכון."));
        phrases.add(new Phrase("איצטבה ", " מדף."));
        phrases.add(new Phrase("איצטגנין ", " אסטרולוג."));
        phrases.add(new Phrase("איצטלה ", " מסווה."));
        phrases.add(new Phrase("איקונין ", " תמונה, דמות."));
        phrases.add(new Phrase("איש אשכולות ", " בקי בנושאים רבים, ורסטילי."));
        phrases.add(new Phrase("איש הישר בעיניו יעשה ", " מצב של אנרכיה, ללא שלטון מרכזי."));
        phrases.add(new Phrase("איש חיל ", " גיבור או אדם מצליח."));
        phrases.add(new Phrase("איש חרמו ", " אויבו."));
        phrases.add(new Phrase("איש מדון ", " בעל נטייה לריב."));
        phrases.add(new Phrase("איש מידות ", " גבוה."));
        phrases.add(new Phrase("איש צפרדע ", " צוללן, אמודאי."));
        phrases.add(new Phrase("אישקוקה ", " שחמט."));
        phrases.add(new Phrase("איש קצוות ", " קיצוני."));
        phrases.add(new Phrase("איש שם ", " מפורסם."));
        phrases.add(new Phrase("אישוש ", " ביסוס, אישור מחדש, חיזוק  של טענה ."));
        phrases.add(new Phrase("אישרור ", " אישור סופי."));
        phrases.add(new Phrase("איתן ", " יציב, חזק, שגיב."));
        phrases.add(new Phrase("איתרע מזלו ", " הדברים היו לרעתו, ביש מזל."));
        phrases.add(new Phrase("אכיפה ", " כפייה."));
        phrases.add(new Phrase("אכל קורצה ", " הלשין."));
        phrases.add(new Phrase("אכסדרה ", " מסדרון, פרוזדור."));
        phrases.add(new Phrase("אכסיומה ", " הנחת יסוד שלא ניתן להוכיחה, אמיתה."));
        phrases.add(new Phrase("אכף ", " לחץ, נטל, מעמסה."));
        phrases.add(new Phrase("אכרומטי ", " חסר צבע."));
        phrases.add(new Phrase("אל יתהלל חוגר כמפתח ", " אל תתפאר לפני מעשה."));
        phrases.add(new Phrase("אל נא באפך ", " אל תכעס."));
        phrases.add(new Phrase("אל נכון ", " בוודאות, ללא ספק, לבטח."));
        phrases.add(new Phrase("אל תסתכל בקנקן אלא במה שיש בתוכו ", " הפנים חשוב יותר מהחיצוניות, לא כל הנוצץ זהב הוא."));
        phrases.add(new Phrase("אל תעמדו על דם רעיכם ", " חושו לעזרת חבריכם."));
        phrases.add(new Phrase("אלגוריה ", " משל."));
        phrases.add(new Phrase("אלה ", " מקל, נבוט."));
        phrases.add(new Phrase("אלה ", " 1. שבועה חמורה;2. קללה, קילוס."));
        phrases.add(new Phrase("אלומה ", " אגודת שיבולים, עומר, עמיר."));
        phrases.add(new Phrase("אלחוש ", " הרדמה."));
        phrases.add(new Phrase("אלטרואיזם ", " אהבת הזולת, הקרבה למען אחרים, זולתנות."));
        phrases.add(new Phrase("אלטרנטיבי ", " חלופי."));
        phrases.add(new Phrase("אליבא דכלא עלמא ", " לפי דעת הכלל."));
        phrases.add(new Phrase("אליבי ", "טענת הנאשם כי בעת ביצוע הפשע לא היה במקום המעשה"));
        phrases.add(new Phrase("אליה ", " זנב הכבשה."));
        phrases.add(new Phrase("אליה וקוץ בה ", " גם בדבר טוב יש פגמים."));
        phrases.add(new Phrase("אלם ", " שתיקה."));
        phrases.add(new Phrase("אלמותי ", " נצחי."));
        phrases.add(new Phrase("אלמלא ", " אם לא, אילו לא, אילולא."));
        phrases.add(new Phrase("אלמנך ", " לוח המציג את עונות השנה."));
        phrases.add(new Phrase("אלסטי ", " גמיש."));
        phrases.add(new Phrase("אלף ", " שור, פר."));
        phrases.add(new Phrase("אלפון ", " ספר שבו הפרטים מסודרים על-פי סדר הא”ב."));
        phrases.add(new Phrase("אמביולנטי ", " דו-ערכי, שיש בו רגשות מעורבים."));
        phrases.add(new Phrase("אמבר ", " מחסן תבואה, אסם, ממגורה."));
        phrases.add(new Phrase("אמברגו ", " הסגר, איסור על הוצאה והבאה של דברים מסוימים למקום מסוים."));
        phrases.add(new Phrase("אמד ", " העריך, שיער גודל או טיב של משהו."));
        phrases.add(new Phrase("אמה ", " 1. מידת אורך;2. האצבע האמצעית ביד, אצבע צרדה."));
        phrases.add(new Phrase("אמה ", " משרתת, שפחה."));
        phrases.add(new Phrase("אמודאי ", " צוללן, איש צפרדע."));
        phrases.add(new Phrase("אמון ", " מיומן."));
        phrases.add(new Phrase("אמוק ", " טירוף, בלבול, תעתועים, עוועים."));
        phrases.add(new Phrase("אמות הסיפים ", " העמודים, התומכים פתח או מבנה מצדדיו."));
        phrases.add(new Phrase("אמורפי ", " חסר צורה."));
        phrases.add(new Phrase("אמיד ", " עשיר."));
        phrases.add(new Phrase("אמיר ", " צמרת."));
        phrases.add(new Phrase("אמפיבי ", " דו חיים, יצור המסוגל להתקיים הן במים והן ביבשה."));
        phrases.add(new Phrase("אמפתיה ", "אהדה, הזדהות."));
        phrases.add(new Phrase("אמרה ", " 1. משפט קצר, פתגם;2. שפת הבד."));
        phrases.add(new Phrase("אמש ", " 1. בלילה שעבר; 2.אתמול."));
        phrases.add(new Phrase("אמתחת ", " שק גדול, תרמיל, צקלון, צרור, אגד."));
        phrases.add(new Phrase("אמתלה ", " תירוץ, עילה, תואנה, גנות."));
        phrases.add(new Phrase("אמת מידה ", " קנה מידה, קריטריון."));
        phrases.add(new Phrase("אנדרטה ", " מצבת זיכרון, יד, גלעד."));
        phrases.add(new Phrase("אנונימי ", " בעילום שם, אלמוני, אינקוגניטו."));
        phrases.add(new Phrase("אנוף ", " נזוף."));
        phrases.add(new Phrase("אנוש ", " חמור מאוד, עלול לגרום למוות."));
        phrases.add(new Phrase("אנטגוניזם ", " התנגדות, ניגוד חריף."));
        phrases.add(new Phrase("אנטומיה ", " חקר מבנה גוף החי והצומח."));
        phrases.add(new Phrase("אנטיספטי ", " סטרילי."));
        phrases.add(new Phrase("אנטיתזה ", " הנחה סותרת."));
        phrases.add(new Phrase("אני ואפסי עוד ", " הבעת יהירות, אגוצנטרי."));
        phrases.add(new Phrase("אניגמה ", " תעלומה, מסתורין."));
        phrases.add(new Phrase("אניגמטי ", " חידתי."));
        phrases.add(new Phrase("אניה ", " בכי, מספד, תאניה."));
        phrases.add(new Phrase("אנין ", " עדין, בעל טעם מעודן, איסטניס."));
        phrases.add(new Phrase("אנכרוניסטי ", " התיישן, עבר זמנו."));
        phrases.add(new Phrase("אנליטי ", " ביקורתי, המפריד דבר לחלקיו."));
        phrases.add(new Phrase("אנסמבל ", " להקת שחקנים או מוסיקאים."));
        phrases.add(new Phrase("אנקה ", " גניחה, צעקה מתוך כאב או צער."));
        phrases.add(new Phrase("אנפילאות ", " נעלי בית, דרדסים."));
        phrases.add(new Phrase("אנקדוטה ", " בדיחה, הלצה."));
        phrases.add(new Phrase("אנרכיה ", " העדר שלטון, אנדרלמוסיה."));
        phrases.add(new Phrase("אנרכיזם ", " שלילת כל שלטון."));
        phrases.add(new Phrase("אנשי שלומו ", " תומכיו."));
        phrases.add(new Phrase("אנתרופולוגיה ", " חקר התפתחות האדם."));
        phrases.add(new Phrase("אסדה ", " רפסודה, דוברה, ארבה, בוצית."));
        phrases.add(new Phrase("אסוך ", " כד לשמן."));
        phrases.add(new Phrase("אסופה ", " קובץ מאמרים, אנתולוגיה."));
        phrases.add(new Phrase("אסופי ", " ילד שנאסף מן הרחוב."));
        phrases.add(new Phrase("אסטרונומי ", " גדול מאוד, עצום."));
        phrases.add(new Phrase("אסימילציה ", " הטמעה, הידמות, התבוללות."));
        phrases.add(new Phrase("אסכולה ", " 1. שיטה, דיסציפלינה, דוקטרינה;2. קבוצה הדוגלת ברעיון מסוים."));
        phrases.add(new Phrase("אסכלה ", " 1. סולם מדרגות, כבש; 2. גריל."));
        phrases.add(new Phrase("אסם ", " מחסן תבואה, ממגורה, אמבר."));
        phrases.add(new Phrase("אסמכתא ", " מקור שאפשר להסתמך עליו."));
        phrases.add(new Phrase("אספלנית ", " פלסטר, תחבושת."));
        phrases.add(new Phrase("אספקלריה ", " ראי."));
        phrases.add(new Phrase("אסקופה ", " סף."));
        phrases.add(new Phrase("אסר מלחמה ", " פתח בקרב."));
        phrases.add(new Phrase("אסרטיבי ", " בטוח בעצמו, עומד על שלו."));
        phrases.add(new Phrase("אף ", " כעס."));
        phrases.add(new Phrase("אפודה ", " מיזע, סווטשרט."));
        phrases.add(new Phrase("אפוטרופוס ", " ממונה לטיפול בקטין, פטרון."));
        phrases.add(new Phrase("אפולוגטיקה ", " הצטדקות."));
        phrases.add(new Phrase("אפוסטריורי ", " למפרע, על מה שכבר נעשה, בדיעבד, מראש."));
        phrases.add(new Phrase("אפוף ", " עטוף, מוקף במשהו."));
        phrases.add(new Phrase("אפוקליפסה ", " חזון אחרית הימים."));
        phrases.add(new Phrase("אפיזודה ", " מקרה, מאורע בודד."));
        phrases.add(new Phrase("אפיל ", " איחר להבשיל."));
        phrases.add(new Phrase("אפילוג ", " אחרית דבר, סיום."));
        phrases.add(new Phrase("אפיפית ", " ופל, ביסקויט, תופין, רקיק, פכסם."));
        phrases.add(new Phrase("אפיקורוס ", " כופר בדת, מין, אתיאיסט."));
        phrases.add(new Phrase("אפיקורסות ", " כפירה."));
        phrases.add(new Phrase("אפיריון ", " מושב שמעליו חופה לנשיאת אנשים."));
        phrases.add(new Phrase("אפס קצהו ", " רק קצת ממנו."));
        phrases.add(new Phrase("אפקט ", " השפעה."));
        phrases.add(new Phrase("אפרופו ", " אגב."));
        phrases.add(new Phrase("אפריורי ", " מראש, מלכתחילה, למפרע."));
        phrases.add(new Phrase("אפרכסת ", " 1. אזנית הטלפון;2. חלקה החיצוני של האוזן."));
        phrases.add(new Phrase("אפרקדן ", " שוכב על הגב, פרקדן."));
        phrases.add(new Phrase("אץ ", " רץ, נחפז, ממהר."));
        phrases.add(new Phrase("אצבע צרדה ", " אמה, האצבע האמצעית."));
        phrases.add(new Phrase("אצבעון ", " כיפת מתכת ששמים על האצבע בשעת התפירה."));
        phrases.add(new Phrase("אצטלה ", " גלימת אדם מכובד."));
        phrases.add(new Phrase("אצעדה ", " צמיד, עדי, משכית."));
        phrases.add(new Phrase("אצר ", " אסף, אגר, צבר."));
        phrases.add(new Phrase("אקוטי ", " 1. חד;  2. חריף, חמור."));
        phrases.add(new Phrase("אקונומי ", " חסכני."));
        phrases.add(new Phrase("אקזוטי ", " יוצא דופן, מרתק עקב זרותו."));
        phrases.add(new Phrase("אקלקטי ", " מלוקט, מקובץ ממקורות שונים."));
        phrases.add(new Phrase("אקסיומה ", " הנחה שאין עליה ערעור."));
        phrases.add(new Phrase("אקסצנטרי ", " חריג, מוזר, תמהוני, ביזארי."));
        phrases.add(new Phrase("אקרן ", " מסך, מרקע, בד."));
        phrases.add(new Phrase("אראל ", " מלאך, כרוב, שרף."));
        phrases.add(new Phrase("ארגומנט ", " טיעון."));
        phrases.add(new Phrase("ארוגני ", " אזור רגיש לגירוי מיני."));
        phrases.add(new Phrase("ארבה ", " סירה שטוחה, רפסודה."));
        phrases.add(new Phrase("ארוגנטי ", " רברבן."));
        phrases.add(new Phrase("ארוזיה ", " שחיקה."));
        phrases.add(new Phrase("ארוכה ", " 1. גלד של פצע; 2. רפואה."));
        phrases.add(new Phrase("ארומה ", " ריח נעים, ניחוח."));
        phrases.add(new Phrase("ארחי פרחי ", " 1. בטלנים, ריקים; 2. נודדים."));
        phrases.add(new Phrase("אריה ", " קטיפה, איסוף  בעיקר תאנים ודבש ."));
        phrases.add(new Phrase("אריח ", " מרצפת."));
        phrases.add(new Phrase("אריסטוקרט ", " אציל, שוע, בעל בעמיו, מרקיז."));
        phrases.add(new Phrase("ארכאי ", " עתיק, מיושן."));
        phrases.add(new Phrase("ארך אפיים ", " סבלן, מתאפק מלכעוס."));
        phrases.add(new Phrase("ארכובה ", " 1. ברך; 2. דבר כפוף כברך."));
        phrases.add(new Phrase("ארכוף ", " טבעת בצד האוכף, שבה שם הרוכב את כף רגלו, משוורת."));
        phrases.add(new Phrase("ארכיב ", " ארכיון, גנזך."));
        phrases.add(new Phrase("ארכיבישוף ", " דרגת כמורה גבוהה."));
        phrases.add(new Phrase("ארכיפלג ", " קבוצת איים."));
        phrases.add(new Phrase("ארעי ", " זמני, קיקיוני, אקראי, בר-חלוף."));
        phrases.add(new Phrase("ארץ גזרה ", " 1. ארץ רחוקה ונידחת; 2. מושבת עונשין."));
        phrases.add(new Phrase("ארצי ", " חומרי, גופני, פיזי, גשמי."));
        phrases.add(new Phrase("ארר ", " קילל, חירף, גידף, גינה, ניאץ."));
        phrases.add(new Phrase("אשמאי ", " חוטא ; בביטוי: אשמאי זקן  חוטא זקן ."));
        phrases.add(new Phrase("אשמורת ", " חלק מהלילה  לרוב שליש ."));
        phrases.add(new Phrase("אשפה ", " נרתיק לחצים, תלי."));
        phrases.add(new Phrase("אשפרה ", " גימור האריג."));
        phrases.add(new Phrase("אתיאיזם ", " כפירה באל, מינות, אפיקורסות."));
        phrases.add(new Phrase("אתיקה ", " תורת המוסר."));
        phrases.add(new Phrase("אתנחתא ", " הפסקה."));
        phrases.add(new Phrase("בא אל אבותיו ", " נפטר  גם “נאסף אל אבותיו ."));
        phrases.add(new Phrase("בא בדברים ", " נשא ונתן, נדבר."));
        phrases.add(new Phrase("בא בימים ", " זקן, קשיש."));
        phrases.add(new Phrase("בא כוח ", " נציג, מורשה, ציר, מיופה כוח."));
        phrases.add(new Phrase("בא כחתף ", " בא לפתע, התקיף פתאום."));
        phrases.add(new Phrase("בא על שכרו ", " קיבל גמול על מעשיו הטובים."));
        phrases.add(new Phrase("בא עליו במקלו ובתרמילו ", " תקף אותו בלהט הוויכוח."));
        phrases.add(new Phrase("באבו ", " בצעירותו."));
        phrases.add(new Phrase("באו מים עד נפש ", " נמאס, עד קצה גבול היכולת."));
        phrases.add(new Phrase("באוש ", " מסריח, מעופש, עבש, מצחין."));
        phrases.add(new Phrase("באותות ובמופתים ", " באופן משכנע, באמצעות הוכחות חותכות."));
        phrases.add(new Phrase("באישון לילה ", " מאוחר בלילה."));
        phrases.add(new Phrase("באשר על כן ", " מכיוון שכך."));
        phrases.add(new Phrase("בבואה ", " דמות, המשתקפת במים או במראה."));
        phrases.add(new Phrase("בביטול ", " בחוסר הערכה, בהתעלמות מערכו של משהו."));
        phrases.add(new Phrase("בגדי חמודות ", " בגדים נאים ומכובדים."));
        phrases.add(new Phrase("בגדי שרד ", " מדים רשמיים."));
        phrases.add(new Phrase("בגינו ", " בגללו, בעטיו."));
        phrases.add(new Phrase("בגפו ", " לבדו."));
        phrases.add(new Phrase("בגרון נטוי ", " ביהירות."));
        phrases.add(new Phrase("בד ", " 1.ענף של עץ, זרד, זלזל, נצר, עפי;2. מסך, אקרן, מרקע."));
        phrases.add(new Phrase("בד בבד ", " תוך כדי, סימולטני."));
        phrases.add(new Phrase("בדותה ", " שקר, כזב."));
        phrases.add(new Phrase("בדימוס ", " לשעבר, בגימלאות."));
        phrases.add(new Phrase("בדיעבד ", " לאחר מעשה, אפוסטריורי."));
        phrases.add(new Phrase("בדלנות ", " פרישה מן הכלל."));
        phrases.add(new Phrase("בדם ליבו ", " בשארית כוחותיו."));
        phrases.add(new Phrase("בדם קר ", " בלא התרגשות, בשיקול דעת קר."));
        phrases.add(new Phrase("בדמי הליל ", " בדממת הליל."));
        phrases.add(new Phrase("בדמי ימיו ", " באמצע חייו."));
        phrases.add(new Phrase("בדעה צלולה ", " בהכרה מלאה, במלוא החושים."));
        phrases.add(new Phrase("בדק בית ", " תיקון פגמים, שיפור."));
        phrases.add(new Phrase("בדק בציציות ", " בדק באופן מעמיק."));
        phrases.add(new Phrase("בהול ", " דחוף מאוד."));
        phrases.add(new Phrase("בהמה גסה ", " בקר."));
        phrases.add(new Phrase("בהמה דקה ", " צאן."));
        phrases.add(new Phrase("בהק ", " זהר."));
        phrases.add(new Phrase("בהרת ", " נמש."));
        phrases.add(new Phrase("בואך ", " הדרך הפונה אל מקום מסוים, בכיוון או בסביבת מקום מסוים."));
        phrases.add(new Phrase("בוהו ", " ריקנות."));
        phrases.add(new Phrase("בוחן כליות ולב ", " כינוי לאל."));
        phrases.add(new Phrase("בוטה ", " חריף, עוקצני, נוקב."));
        phrases.add(new Phrase("בולבוס ", " תפוח אדמה."));
        phrases.add(new Phrase("בולמוס ", " רעב חזק, תאווה."));
        phrases.add(new Phrase("בומבסטי ", " מנופח."));
        phrases.add(new Phrase("בונה פידה ", " באמת ובתמים, בתום לב."));
        phrases.add(new Phrase("בוסר ", " לא בשל."));
        phrases.add(new Phrase("בוסתן ", " גן."));
        phrases.add(new Phrase("בוצר ", " קוטף ענבים."));
        phrases.add(new Phrase("בוקה ומבוקה ומבולקה ", " שממון גמור, חורבן מלא."));
        phrases.add(new Phrase("בוקי סריקי ", " דברי הבאי והבל, להג."));
        phrases.add(new Phrase("בוקר ", " מגדל בקר."));
        phrases.add(new Phrase("בור ", " 1. שדה לא מעובד; 2. חסר השכלה, נבער."));
        phrases.add(new Phrase("בורדו ", " אדום כהה."));
        phrases.add(new Phrase("בור סוד שאינו מאבד טיפה ", " כינוי לאדם בעל זכרון טוב."));
        phrases.add(new Phrase("בור שומן ", " עסק רווחי."));
        phrases.add(new Phrase("בורית ", " סבון."));
        phrases.add(new Phrase("בורסקאי ", " מעבד עורות."));
        phrases.add(new Phrase("בושש ", " התעכב, התמהמה, איחר."));
        phrases.add(new Phrase("בזיך ", " ספל, קערית."));
        phrases.add(new Phrase("בזעיר אנפין ", " בקנה מידה קטן."));
        phrases.add(new Phrase("בזק ", " פיזר, זרה, זורר."));
        phrases.add(new Phrase("בחבו ", " בתוכו."));
        phrases.add(new Phrase("בחטף ", " במהירות יתרה, בחיפזון, לפתע."));
        phrases.add(new Phrase("בחל ", " נגעל, תיעב, קץ, היה לו לזרא."));
        phrases.add(new Phrase("בחרוק שיניים ", " התאפקות שלא לחשוף תחושות של רוגז."));
        phrases.add(new Phrase("בחרות ", " ראשית תקופת הבגרות שבתום תקופת הנעורים."));
        phrases.add(new Phrase("בטאון ", " עיתון או כתב-עת."));
        phrases.add(new Phrase("בטן רכה ", " מקום רגיש, נקודת תורפה."));
        phrases.add(new Phrase("בטנה ", " בד המצפה בגדים או תיקים מצדם הפנימי."));
        phrases.add(new Phrase("בטש ", " דרך, רמס, כבש, דרס."));
        phrases.add(new Phrase("ביאה ", " 1. פרוזדור, כניסה, מבואה; 2. הזדווגות."));
        phrases.add(new Phrase("ביאר ", " הסביר, פירש."));
        phrases.add(new Phrase("ביב ", " ביוב, תעלת שופכין."));
        phrases.add(new Phrase("ביבר ", " גן חיות."));
        phrases.add(new Phrase("ביב שופכין ", " ביוב, תעלת שופכין  ראה גם “ביב” ."));
        phrases.add(new Phrase("ביגמיה ", " נישואי גבר אחד עם שתי נשים במקביל."));
        phrases.add(new Phrase("ביד ברזל ", " ביד קשה, ללא רחמים."));
        phrases.add(new Phrase("ביד רכה ", " בדרכי נועם, בכפפות של משי."));
        phrases.add(new Phrase("ביזארי ", " מוזר, חריג, יוצא דופן."));
        phrases.add(new Phrase("ביזוי ", " זילזול."));
        phrases.add(new Phrase("ביזור ", " פיזור סמכויות."));
        phrases.add(new Phrase("ביכר ", " העדיף."));
        phrases.add(new Phrase("בין המצרים ", " ללא מוצא, בין הפטיש ובין הסדן."));
        phrases.add(new Phrase("בין השורות ", " במרומז, בין השיטין."));
        phrases.add(new Phrase("בין השמשות ", " לפנות ערב, בין ערביים, דמדומים."));
        phrases.add(new Phrase("בינאום ", " הפיכת שטח לבינלאומי."));
        phrases.add(new Phrase("בינארי ", " עשוי משני מרכיבים, דיכוטומי, דואלי."));
        phrases.add(new Phrase("בינה ", " שכל, תבונה."));
        phrases.add(new Phrase("בין ערביים ", " לפנות ערב, דמדומים, בין השמשות."));
        phrases.add(new Phrase("ביעור ", " סילוק, השמדה, חיסול שיטתי."));
        phrases.add(new Phrase("ביעות ", " סיוט, פחד, יראה, בלהה, חת."));
        phrases.add(new Phrase("ביעף ", " במהירות, בחיפזון, בבהילות."));
        phrases.add(new Phrase("ביצרון ", " מבצר, בירנית, מילוא, עופל."));
        phrases.add(new Phrase("בירא ", " כרת, עקר עצים."));
        phrases.add(new Phrase("בירך על המוגמר ", " סיים בהצלחה את שהתחיל."));
        phrases.add(new Phrase("בישוף ", " דרגת כמורה גבוהה."));
        phrases.add(new Phrase("בית בד ", " בית מלאכה בו מייצרים שמן."));
        phrases.add(new Phrase("בית גנזים ", " ארכיון."));
        phrases.add(new Phrase("בית הלל ", " כינוי למי שנוטה להקל בדין."));
        phrases.add(new Phrase("בית מטבחיים ", " משחטה."));
        phrases.add(new Phrase("בית מרזח ", " פאב, מסבאה, ממזגה."));
        phrases.add(new Phrase("בית נבחרים ", " פרלמנט."));
        phrases.add(new Phrase("בית נכות ", " מוזיאון."));
        phrases.add(new Phrase("בית נתיבות ", " תחנה, מסוף, טרמינל."));
        phrases.add(new Phrase("בית שמאי ", " כינוי למי שנוטה להחמיר בדין."));
        phrases.add(new Phrase("בית תמחוי ", " מטבח ציבורי לנזקקים."));
        phrases.add(new Phrase("ביתוק ", " שיסוע, ביתור."));
        phrases.add(new Phrase("ביתור ", " חיתוך, שיסוף, ביתוק, פילוח."));
        phrases.add(new Phrase("בכדי ", " לשווא, לריק, לחינם."));
        phrases.add(new Phrase("בכובד ראש ", " ברצינות, מתוך שיקול דעת."));
        phrases.add(new Phrase("בכי תמרורים ", " בכי מר, בדמעות שליש."));
        phrases.add(new Phrase("בכייה לדורות ", " אסון שאין לו סוף."));
        phrases.add(new Phrase("בכל רמח איבריו ", " כל כולו, בכל הוויתו."));
        phrases.add(new Phrase("בכפיפה אחת ", " ביחד, בצוותא."));
        phrases.add(new Phrase("בכר ", " גמל צעיר."));
        phrases.add(new Phrase("בכרה ", " נאקה צעירה."));
        phrases.add(new Phrase("בלאט ", " בסתר, בחשאי, בצנעה."));
        phrases.add(new Phrase("בלב ולב ", " במרמה, בחוסר כנות."));
        phrases.add(new Phrase("בלב שלם ", " ביושר, באמת ובתמים."));
        phrases.add(new Phrase("בלהה ", " פחד, בעתה, חיל, פלצות."));
        phrases.add(new Phrase("בלואים ", " בגדים מרופטים."));
        phrases.add(new Phrase("בלוי ", " ישן, מרופט, בלה, מהוה."));
        phrases.add(new Phrase("בלול ", " מעורב, מעורבב."));
        phrases.add(new Phrase("בלום ", " סתום, מלא, גדוש."));
        phrases.add(new Phrase("בלטריסטיקה ", " ספרות יפה."));
        phrases.add(new Phrase("בלי חשך ", " ללא הפסקה, בלי הרף."));
        phrases.add(new Phrase("בלי מצרים ", " בלי גבול."));
        phrases.add(new Phrase("בלימה ", " כלום, אין, אפס."));
        phrases.add(new Phrase("בליסטרא ", " מכשיר מלחמה לזריקת אבנים, מרגמה."));
        phrases.add(new Phrase("בלן ", " עובד בבית מרחץ."));
        phrases.add(new Phrase("בלע ", " מרמה, שחיתות."));
        phrases.add(new Phrase("בלשון סגי נהור ", " שימוש בלשון במשמעות הפוכה."));
        phrases.add(new Phrase("בלתי אמצעי ", " ישיר, ללא תיווך."));
        phrases.add(new Phrase("בלתי נדלה ", " שאינו נגמר, אינסופי."));
        phrases.add(new Phrase("בלתי נלאה ", " חזק, נמרץ, כוחו במותניו."));
        phrases.add(new Phrase("במזיד ", " בכוונה להרע."));
        phrases.add(new Phrase("במטותא ", " בבקשה, אנא."));
        phrases.add(new Phrase("במלוא הקיטור ", " במלוא המרץ."));
        phrases.add(new Phrase("במפגיע ", " בתקיפות, באסרטיביות."));
        phrases.add(new Phrase("במצב נחושה ", " 1. בעקשנות; 2. בחוצפה."));
        phrases.add(new Phrase("במתק שפתיים ", " בדיבור מתחנחן."));
        phrases.add(new Phrase("במשורה ", " בצמצום."));
        phrases.add(new Phrase("בן אלמוות ", " בעל חיי נצח."));
        phrases.add(new Phrase("בן בלי שם ", " בעל מעמד נחות."));
        phrases.add(new Phrase("בן בליעל ", " נבל, רשע, בן עוולה."));
        phrases.add(new Phrase("בן חורין ", " אדם חופשי."));
        phrases.add(new Phrase("בן כלאיים ", " צאצא של צמחים או בעלי"));
        phrases.add(new Phrase("בן סורר ומורה ", " מורד, אינו סר למרות הוריו."));
        phrases.add(new Phrase("בן תשחורת ", " צעיר, עול ימים."));
        phrases.add(new Phrase("בנאלי ", " שכיח, נדוש, שגרתי."));
        phrases.add(new Phrase("בנה בחול ", " טרח לשווא."));
        phrases.add(new Phrase("בנוי לתלפיות ", " 1. בעל גוף שרירי; 2. מתנוסס ברוב הדרו."));
        phrases.add(new Phrase("בניחותא ", " באיטיות, בנחת, בשופי."));
        phrases.add(new Phrase("בניין אב ", " יסוד, אבטיפוס, פרוטוטיפ."));
        phrases.add(new Phrase("בסירה אחת ", " גורל משותף."));
        phrases.add(new Phrase("בעברי פי פחת ", " במקום מסוכן."));
        phrases.add(new Phrase("בעור שיניו ", " נמלט ברגע האחרון."));
        phrases.add(new Phrase("בעטיו ", " בגללו, בגינו."));
        phrases.add(new Phrase("בעידנא דריתחא ", " בשעת כעס."));
        phrases.add(new Phrase("בעיצומו ", " בשיאו."));
        phrases.add(new Phrase("בעל אוב ", " קוסם המעלה רוחות מתים לניחוש עתידות."));
        phrases.add(new Phrase("בעל אף ", " כעסן."));
        phrases.add(new Phrase("בעל בשר ", " שמן, בעל גוף."));
        phrases.add(new Phrase("בעל כרחו ", " שלא מרצונו."));
        phrases.add(new Phrase("בעל קומה ", " גבוה."));
        phrases.add(new Phrase("בעלמא ", " סתם, ללא כוונה."));
        phrases.add(new Phrase("בעצלתיים ", " באיטיות מרובה."));
        phrases.add(new Phrase("בערוב ימיו ", " בסוף חייו."));
        phrases.add(new Phrase("בעתה ", " פחד, חיל, פיק, פלצות."));
        phrases.add(new Phrase("בפוטנציה ", " באופן שעדיין לא מומש."));
        phrases.add(new Phrase("בפרהסיה ", " בגלוי, קבל עם ועדה."));
        phrases.add(new Phrase("בצדיה ", " בכוונה רעה."));
        phrases.add(new Phrase("בצוותא ", " ביחד."));
        phrases.add(new Phrase("בציר ", " קטיף ענבים."));
        phrases.add(new Phrase("בצע ", " פרס, חתך."));
        phrases.add(new Phrase("בקי ", " מומחה, יודע דבר על בוריו."));
        phrases.add(new Phrase("בקק ", " החריב."));
        phrases.add(new Phrase("בר ", " 1. נקי; 2. חוץ; 3. בן; 4. תבואה."));
        phrases.add(new Phrase("בר אוריין ", " תלמיד חכם, למדן, בן תורה."));
        phrases.add(new Phrase("בר בי רב ", " תלמיד."));
        phrases.add(new Phrase("בר דעת ", " חכם."));
        phrases.add(new Phrase("בר חלוף ", " זמני, ארעי."));
        phrases.add(new Phrase("בר לבב ", " ישר, תמים."));
        phrases.add(new Phrase("בר מינן ", " מת, הלך בדרך כל הארץ."));
        phrases.add(new Phrase("בר סמכא ", " מומחה, בקי."));
        phrases.add(new Phrase("בר פלוגתא ", " יריב, בעל מחלוקת."));
        phrases.add(new Phrase("בר קיימא ", " יציב, מתקיים לאורך זמן."));
        phrases.add(new Phrase("בר סמכא ", " מומחה."));
        phrases.add(new Phrase("בראש חוצות ", " בגלוי, בפרהסיה."));
        phrases.add(new Phrase("בראש מעיניו ", " בראש סדר העדיפויות שלו."));
        phrases.add(new Phrase("ברוד ", " מכוסה כתמים או נקודות, מנומר."));
        phrases.add(new Phrase("ברוטלי ", " אכזרי."));
        phrases.add(new Phrase("ברומו של עולם ", " חשוב."));
        phrases.add(new Phrase("ברי ", " ברור, ודאי."));
        phrases.add(new Phrase("בריה ", " יצור, בעל חיים, בן תמותה."));
        phrases.add(new Phrase("בריח ", " מוט לנעילת הדלת."));
        phrases.add(new Phrase("בריקדה ", " מחסום, מתרס."));
        phrases.add(new Phrase("ברכה לבטלה ", " טרחה המושקעת לריק."));
        phrases.add(new Phrase("ברנש ", " בן אדם."));
        phrases.add(new Phrase("בשוגג ", " לא בכוונה."));
        phrases.add(new Phrase("בשופי ", " בנחת, בניחותא, מעדנות."));
        phrases.add(new Phrase("בשן ועין ", " בנזק כבד."));
        phrases.add(new Phrase("בשר ודם ", " בן תמותה."));
        phrases.add(new Phrase("בשר מבשרו ", " קרוב אליו, חשוב לו כבן משפחה."));
        phrases.add(new Phrase("בת קול ", " הד."));
        phrases.add(new Phrase("בתה ", " שדה מוזנח ושומם, ישימון."));
        phrases.add(new Phrase("גאה ", " התרומם, עלה."));
        phrases.add(new Phrase("גבה לבו ", " התגאה, התייהר, התרברב."));
        phrases.add(new Phrase("גבהו ממנו הדברים ", " לא הבין."));
        phrases.add(new Phrase("גבו אל הקיר ", " ללא מוצא, בין המצרים."));
        phrases.add(new Phrase("גבין ", " גבה."));
        phrases.add(new Phrase("גביר ", " אדם עשיר, אמיד."));
        phrases.add(new Phrase("גבנון ", " עקמומיות של הגב, חטוטרת."));
        phrases.add(new Phrase("גבר ", " תרנגול, שכוי."));
        phrases.add(new Phrase("גבר אגרופו ", " התחזק."));
        phrases.add(new Phrase("גברה ידו ", " ניצח."));
        phrases.add(new Phrase("גברתן ", " בעל כוח, בעל גוף."));
        phrases.add(new Phrase("גד ", " מזל, אושר, הצלחה, פיס, פור."));
        phrases.add(new Phrase("גדה ", " שפת הנהר."));
        phrases.add(new Phrase("גדוד ", " חתוך."));
        phrases.add(new Phrase("גדולות ונצורות ", " דברים גדולים ומפתיעים."));
        phrases.add(new Phrase("גדיד ", " קטיף תמרים."));
        phrases.add(new Phrase("גדיל ", " קצוות חוטים, ציצית."));
        phrases.add(new Phrase("גדיש ", " ערמת תבואה שנקצרה."));
        phrases.add(new Phrase("גדש ", " צבר, ערם, מילא יתר על המידה."));
        phrases.add(new Phrase("גהה ", " רפואה, מרפא, צרי."));
        phrases.add(new Phrase("גהות ", " הגיינה."));
        phrases.add(new Phrase("גהר ", " התכופף, רכן, שח, גחן, השתופף."));
        phrases.add(new Phrase("גו ", " 1. פנים, תוך; 2. גב, גוף."));
        phrases.add(new Phrase("גוב ", " בור, מאורה."));
        phrases.add(new Phrase("גוב אריות ", " מקום מסוכן."));
        phrases.add(new Phrase("גוויל ", " קלף, דף מספר עתיק."));
        phrases.add(new Phrase("גוזמה ", " הפרזה, דברי הבאי."));
        phrases.add(new Phrase("גולל ", " אבן עגולה ששימשה לכיסוי פי הבאר."));
        phrases.add(new Phrase("גולמי ", " בלתי מעובד."));
        phrases.add(new Phrase("גומה ", " חור, שקע."));
        phrases.add(new Phrase("גומחה ", " שקע, מגרעת."));
        phrases.add(new Phrase("גוץ ", " נמוך ושמנמן."));
        phrases.add(new Phrase("גורס ", " לועס."));
        phrases.add(new Phrase("גושפנקה ", " חותם, אישור."));
        phrases.add(new Phrase("גז ", " 1. צמר שנגזז; 2. נעלם, עבר, התפוגג."));
        phrases.add(new Phrase("גזוזטרה ", " מרפסת."));
        phrases.add(new Phrase("גזיר ", " חתיכה, נתח, פיסה."));
        phrases.add(new Phrase("גזירה ", " פקודה שיש בה איסור."));
        phrases.add(new Phrase("גזר כליה ", " הביא לסופו, חיסל אותו."));
        phrases.add(new Phrase("גזרה שווה ", " היקש, השוואה בין שני עניינים הדומים זה לזה בתכנם או בצורתם."));
        phrases.add(new Phrase("גחמה", "רצון פתאומי שקשה להסבירו, עיקשות, קפריזה."));
        phrases.add(new Phrase("גחן ", " התכופף, רכן, שחה, גהר."));
        phrases.add(new Phrase("גיא ", " עמק."));
        phrases.add(new Phrase("גיבב ", " צבר, ערם, קושש, גדש."));
        phrases.add(new Phrase("גיבח", "קרח בראשו מצד המצח."));
        phrases.add(new Phrase("גיבן ", " שגבו מעוקם, בעל חטוטרת."));
        phrases.add(new Phrase("גידם ", " קטוע יד, גידע."));
        phrases.add(new Phrase("גידף ", " קילל, חירף, גינה, ניאץ, ארר."));
        phrases.add(new Phrase("גיור ", " המרת דתו של אדם ליהדות."));
        phrases.add(new Phrase("גילה את קלפיו ", " חשף את כוונותיו."));
        phrases.add(new Phrase("גילה טפח וכיסה טפחיים ", " העלים יותר משגילה."));
        phrases.add(new Phrase("גילו את אזנו ", " גילו לו."));
        phrases.add(new Phrase("גילוי דעת ", " מאמר."));
        phrases.add(new Phrase("גילום ", " עיצוב, מתן צורה מוחשית."));
        phrases.add(new Phrase("גילופין ", " שכרות קלה."));
        phrases.add(new Phrase("גימא ארץ ", " דהר מהר."));
        phrases.add(new Phrase("גינה ", " קילל, חירף, קילס, ניאץ, גידף."));
        phrases.add(new Phrase("גינונים ", " נימוסים והליכות, דרך ארץ."));
        phrases.add(new Phrase("גיס חמישי ", " כינוי לבוגדים מבית, סוס טרויאני."));
        phrases.add(new Phrase("גירסא דינקותא ", " הידע שלמד אדם בילדותו."));
        phrases.add(new Phrase("גל ", " ערמה, תל, חשרה, צבר."));
        phrases.add(new Phrase("גלד ", " קרום יבש, המכסה את מקום הפציעה בעור."));
        phrases.add(new Phrase("גלובלי ", " כלל עולמי, אוניברסלי."));
        phrases.add(new Phrase("גלום ", " מקופל, מגולל, חבוי בפנים."));
        phrases.add(new Phrase("גלוסקמה ", " ארון קבורה, סרקופג."));
        phrases.add(new Phrase("גלופה ", " לוח עם תבליטי אותיות המשמש להדפסתן."));
        phrases.add(new Phrase("גלוריפיקציה ", " האדרה."));
        phrases.add(new Phrase("גליל ", " אזור, מחוז, חבל, פלך, נפה."));
        phrases.add(new Phrase("גלל ", " גילגל, טילטל."));
        phrases.add(new Phrase("גלל חרפה מעליו ", " החזיר אליו את כבודו."));
        phrases.add(new Phrase("גלמוד ", " בודד, ערירי, חשוך בנים."));
        phrases.add(new Phrase("גלעין ", " חרצן, גרעין של פרי."));
        phrases.add(new Phrase("גלקסיה ", " מערכת כוכבים."));
        phrases.add(new Phrase("גמא ", " שתה, לגם, גמע."));
        phrases.add(new Phrase("גמא מרחקים ", " עבר דרך ארוכה."));
        phrases.add(new Phrase("גמלוני ", " גבוה, ארוך, תמיר, רם, כיפח."));
        phrases.add(new Phrase("גמר אומר ", " החליט, גמר בליבו."));
        phrases.add(new Phrase("גמר עליו את ההלל ", " שיבח, קילס, הרים את קרנו, קשר כתרים."));
        phrases.add(new Phrase("גנב את ליבו ", " רימה, גנב את דעתו."));
        phrases.add(new Phrase("גנוז ", " נסתר, כמון, ספון, כמוס, צפון."));
        phrases.add(new Phrase("גנזך ", " ארכיון, ארכיב."));
        phrases.add(new Phrase("גנראטור ", " מתקן ליצור חשמל  ראה גם “מחולל” ו”טורבינה” ."));
        phrases.add(new Phrase("גסטרונומיה ", " אמנות הבישול, קולינרי."));
        phrases.add(new Phrase("גפה ", " 1. שפה; 2. החלק העליון בנעל, שבשוליו השרוכים."));
        phrases.add(new Phrase("גפיים ", " אברי התנועה, הידיים והרגליים בבני אדם."));
        phrases.add(new Phrase("גפיר ", " שומר, שוטר, זקיף, נוטר."));
        phrases.add(new Phrase("גץ ", " ניצוץ שביב אש."));
        phrases.add(new Phrase("גר ", " אדם שבא לגור בארץ זרה, נוכרי."));
        phrases.add(new Phrase("גרדום ", " גיליוטינה."));
        phrases.add(new Phrase("גרוגרת ", " תאנה מיובשת, דבלה."));
        phrases.add(new Phrase("גרוטסקי ", " מגוחך, נלעג."));
        phrases.add(new Phrase("גרום ", " בעל עצמות בולטות."));
        phrases.add(new Phrase("גרידא ", " אך ורך, בלבד, ותו לא."));
        phrases.add(new Phrase("גרם ", " 1. עצם; 2. גוף."));
        phrases.add(new Phrase("גרנדיוזי ", " מפואר, נשגב, נאדר, עצום."));
        phrases.add(new Phrase("גרס ", " טען."));
        phrases.add(new Phrase("גרעון ", " חוסר, הפסד, חסך, פחת."));
        phrases.add(new Phrase("גשם זלעפות ", " גשם כבד וסוער."));
        phrases.add(new Phrase("גשם נדבות ", " גשם היורד בעתו ובשפע, גשם ברכה."));
        phrases.add(new Phrase("גשמי ", " חומרי, גופני, פיזי."));
        phrases.add(new Phrase("גת ", " בור, שדורכים בו ענבים ליין"));
        phrases.add(new Phrase("ד’ אמות ", " מקום מצומצם, הסביבה הקרובה לאדם."));
        phrases.add(new Phrase("דא עקא ", " זו הצרה."));
        phrases.add(new Phrase("דאבה ", " צער, יגון, דכדוך, תוגה, נכאים."));
        phrases.add(new Phrase("דאז ", " בעת ההיא."));
        phrases.add(new Phrase("דאיה ", " ריחוף באוויר."));
        phrases.add(new Phrase("דבוקה ", " 1. צרור פצצות; 2. קבוצת צנחנים."));
        phrases.add(new Phrase("דבלה ", " גוש תאנים מיובשות, גרוגרת."));
        phrases.add(new Phrase("דבלול ", " 1. קצה חוט היוצא מבד; קווצת שיער על המצח."));
        phrases.add(new Phrase("דבקה לשונו לחיכו ", " שתק, נאלם."));
        phrases.add(new Phrase("דבקה נפשו ", " אהב."));
        phrases.add(new Phrase("דבר אל העצים ואל האבנים! ", " אין עונה, אין תגובה, דיבור לאוזניים ערלות."));
        phrases.add(new Phrase("דבר בעיתו ", " דבר שנעשה בזמן המתאים."));
        phrases.add(new Phrase("דבר דבור על אופניו ", " עניין ערוך כהלכה."));
        phrases.add(new Phrase("דברי חלקות ", " חנופה."));
        phrases.add(new Phrase("דברי כיבושין ", " דברי תוכחה ומוסר."));
        phrases.add(new Phrase("דברי סרק ", " שטויות."));
        phrases.add(new Phrase("דברי קילוסין ", " מחמאות, תשבחות."));
        phrases.add(new Phrase("דברים בטלים ", " דברים לא חשובים."));
        phrases.add(new Phrase("דברים בעלמא ", " פטפוטים, עורבא פרח."));
        phrases.add(new Phrase("דברים העומדים ברומו של עולם ", " דברים נעלים וחשובים."));
        phrases.add(new Phrase("דברים כדורבנות ", " אמירה חריפה והחלטית."));
        phrases.add(new Phrase("דבשה ", " נוזל מתוק, שנוצר בהפקת סוכר."));
        phrases.add(new Phrase("דגה ", " שם קיבוצי לכל הדגים."));
        phrases.add(new Phrase("דגול ", " אדם נכבד, חשוב, ידוע."));
        phrases.add(new Phrase("דגל לבן ", " דגל המסמל כניעה או הפסקת פעולות קרב."));
        phrases.add(new Phrase("דדוקציה ", " הסקה מהכלל אל הפרט."));
        phrases.add(new Phrase("דה יורה ", " להלכה, תיאורטית, בכח."));
        phrases.add(new Phrase("דה פקטו ", " למעשה, בפועל בדיעבד."));
        phrases.add(new Phrase("דהוי ", " שצבעו נחלש והחוויר."));
        phrases.add(new Phrase("דהיינו ", " כלומר."));
        phrases.add(new Phrase("דו פרצופי ", " צבוע, חסר כנות."));
        phrases.add(new Phrase("דואלי ", " בעל שני צדדים, דיכוטומי."));
        phrases.add(new Phrase("דוברה ", " רפסודה, אסדה, ארבה."));
        phrases.add(new Phrase("דוגמה ", " הנחה שמתקבלת כאמת מוחלטת."));
        phrases.add(new Phrase("דוגמטי ", " דבר מוסכם שאין לערער עליו."));
        phrases.add(new Phrase("דודים ", " אהבים."));
        phrases.add(new Phrase("דווי ", " כאב, מיוסר, אבל, נכא, מדוכדך."));
        phrases.add(new Phrase("דו-חי ", " בעל חיים החי הן במים והן ביבשה."));
        phrases.add(new Phrase("דוחן ", " סוג תבואה, דגן."));
        phrases.add(new Phrase("דומיננטי ", " ראשי, עיקרי, בולט."));
        phrases.add(new Phrase("דומם ", " בשקט, בדומיה, חרש, בלאט."));
        phrases.add(new Phrase("דומן ", " זבל, זוהמה, מיאוס, סחי."));
        phrases.add(new Phrase("דופי ", " פגם, גנאי."));
        phrases.add(new Phrase("דופליקט ", " העתק."));
        phrases.add(new Phrase("דוק ", " שכבה דקיקה, קרום דקיק."));
        phrases.add(new Phrase("דוקומנטרי ", " תיעודי."));
        phrases.add(new Phrase("דוקטרינה ", " שיטה, תורה, דיסציפלינה."));
        phrases.add(new Phrase("דורון ", " מתנה, שי, מנחה, אשכר, אתנן."));
        phrases.add(new Phrase("דחה אותו בלך ושוב ", " התחמק ממתן תשובה ברורה."));
        phrases.add(new Phrase("דחי ", " כישלון, תקלה, פוקה, רועץ."));
        phrases.add(new Phrase("דחיות בקש ", " תירוצים קלושים."));
        phrases.add(new Phrase("דחפור ", " טרקטור החופר ומזיז סלעים, בולדוזר."));
        phrases.add(new Phrase("דחק את הקץ ", " לחץ להקדים את הסוף מתוך חוסר סבלנות."));
        phrases.add(new Phrase("דחק את רגליו ", " תפס את מקומו."));
        phrases.add(new Phrase("דטרמיניזם ", " אמונה שהכל נקבע מראש ללא אפשרות שינוי."));
        phrases.add(new Phrase("דיאגנוסטי ", " מאבחן."));
        phrases.add(new Phrase("דיאכרוני ", " ערוך לפי התפתחות הסטורית."));
        phrases.add(new Phrase("דיאלוג ", " רב שיח, שיחה בת שני משתתפים לפחות."));
        phrases.add(new Phrase("דיאלקטי ", " וכחני, המשקף ניגודים."));
        phrases.add(new Phrase("דיבה ", " דברי גנאי, לעז, לשון הרע."));
        phrases.add(new Phrase("דיבוב ", " גרימה לכך שמישהו ידבר."));
        phrases.add(new Phrase("דיבידנד ", " חלק מסוים מן הרווחים, המתחלקים בין בעלי החברה."));
        phrases.add(new Phrase("דיבר אל ליבו ", " פייס אותו, שכנע אותו."));
        phrases.add(new Phrase("דיבר גבוהה גבוהה ", " דיבר בשפה נמלצת."));
        phrases.add(new Phrase("דיבר סרה ", " גינה, השמיץ, ביזה."));
        phrases.add(new Phrase("דיבר על ליבו ", " ניסה לשכנע אותו."));
        phrases.add(new Phrase("דידוי ", " הליכה בדילוגים או בקפיצות."));
        phrases.add(new Phrase("דידקטי ", " קשור בהוראה, לימודי, מאלף."));
        phrases.add(new Phrase("דיונה ", " חולית, גבעת חול."));
        phrases.add(new Phrase("דיוקן ", " תיאור פניו של אדם."));
        phrases.add(new Phrase("דיוטה ", " קומה בבניין."));
        phrases.add(new Phrase("דיכוטומיה ", " התפצלות, חלוקה לשניים."));
        phrases.add(new Phrase("דילטאנט ", " בעל ידיעות שטחיות, הדיוט."));
        phrases.add(new Phrase("דילמה ", " בעיה, התלבטות."));
        phrases.add(new Phrase("דין ", " שופט."));
        phrases.add(new Phrase("דין ודברים ", " ויכוח, טענות ומענות."));
        phrases.add(new Phrase("דין פרוטה כדין מאה ", " יש להתייחס לדברים פחותי ערך כמו ליקרים."));
        phrases.add(new Phrase("דינאמי ", " מתפתח."));
        phrases.add(new Phrase("דיסוננס ", " חוסר התאמה, צרימה."));
        phrases.add(new Phrase("דיסציפלינה ", " שיטה, תורה, אסכולה."));
        phrases.add(new Phrase("דיסקרימינציה ", " אפליה."));
        phrases.add(new Phrase("דיפוזי ", " חדיר."));
        phrases.add(new Phrase("דיפון ", " חיזוק דפנות של בור."));
        phrases.add(new Phrase("דיצה ", " שמחה, ששון, עליצות, משוש."));
        phrases.add(new Phrase("דיקטטור ", " שליט יחיד, דספוט, אוטוקרט."));
        phrases.add(new Phrase("דירבון ", " זירוז, האצה."));
        phrases.add(new Phrase("דירקטוריון ", " מועצת המנהלים של חברה או מוסד."));
        phrases.add(new Phrase("דירת שרד ", " מעון רשמי של בעלי תפקיד."));
        phrases.add(new Phrase("דך ", " מסכן, רצוץ, מעונה."));
        phrases.add(new Phrase("דכי ", " שאון הגלים."));
        phrases.add(new Phrase("דל ", " עני, אביון, חלכאי, דלפון, מך, רש."));
        phrases.add(new Phrase("דל אנפין ", " זעיר."));
        phrases.add(new Phrase("דלדול ", " הפחתה בכמות או איכות של דבר."));
        phrases.add(new Phrase("דלוח ", " עכור, לא צלול."));
        phrases.add(new Phrase("דלמטי ", " סןג כלב אשר על פרוותו הלבנה נקודות שחורות."));
        phrases.add(new Phrase("דלעיל ", " שלמעלה, שנזכר קודם."));
        phrases.add(new Phrase("דלפון ", " עני, אביון, דל, מך, חסר כל."));
        phrases.add(new Phrase("דמגוג ", " בעל כושר שכנוע, רטוריקן."));
        phrases.add(new Phrase("דמדום ", " הזיה."));
        phrases.add(new Phrase("דמדומים ", " זמן השקיעה או הזריחה."));
        phrases.add(new Phrase("דמו בראשו ", " נושא באחריות על מעשיו."));
        phrases.add(new Phrase("דמוגרפיה ", " חקר הרכב האוכלוסיה והשתנותה."));
        phrases.add(new Phrase("דמוני ", " שטני."));
        phrases.add(new Phrase("דמוקרטיה ", " שלטון העם, השתתפות האזרח בקבלת החלטות."));
        phrases.add(new Phrase("דמי ", " שקט, דממה, דומייה."));
        phrases.add(new Phrase("דמיון ", " 1. כמו, דומה למשהו; 2. הגיית דברים במחשבה אשר אינם קיימים במציאות."));
        phrases.add(new Phrase("דמי לא יחרץ ", " שוחד, שלמונים, בצע."));
        phrases.add(new Phrase("דמי ימיו ", " בצעירותו."));
        phrases.add(new Phrase("דמים ", " כסף."));
        phrases.add(new Phrase("דמעות שליש ", " בכי גדול."));
        phrases.add(new Phrase("דמעות תנין ", " בכי מתוך צביעות."));
        phrases.add(new Phrase("דן ברותחין ", " שפט בחומרה, בית שמאי."));
        phrases.add(new Phrase("דנן ", " זה, המדובר, הנזכר לעיל."));
        phrases.add(new Phrase("דספוט ", " רודן, עריץ, טירן, דיקטטור."));
        phrases.add(new Phrase("דעיכה ", " היחלשות, גוויעה, התנוונות."));
        phrases.add(new Phrase("דעתו גסה עליו ", " מתרברב."));
        phrases.add(new Phrase("דעתו נוחה מ ", " הוא מרוצה מ-."));
        phrases.add(new Phrase("דעתן ", " תקיף בדעתו, יודע מה הוא רוצה."));
        phrases.add(new Phrase("דפוס ", " תבנית, מסגרת, צורה קבועה."));
        phrases.add(new Phrase("דפורמציה ", " עיוות צורה."));
        phrases.add(new Phrase("דפיטיזם ", " תבוסתנות."));
        phrases.add(new Phrase("דפיציט ", " גרעון."));
        phrases.add(new Phrase("דפנסיבה ", " מגננה."));
        phrases.add(new Phrase("דפתר ", " פנקס, מחברת, קונטרס."));
        phrases.add(new Phrase("דק ", " עיין, בחן היטב, דקדק."));
        phrases.add(new Phrase("דק גו ", " רזה, כחוש, צנום."));
        phrases.add(new Phrase("דקדוקי עניות ", " דיוק מופרז, נוקדנות."));
        phrases.add(new Phrase("דקדנס ", " ירידה, שקיעה, התנוונות."));
        phrases.add(new Phrase("דקדקן ", " מקפיד על כל פרט באופן מוגזם."));
        phrases.add(new Phrase("דר ", " גר."));
        phrases.add(new Phrase("דראון ", " בושה, חרפה, כלימה."));
        phrases.add(new Phrase("דראון עולם ", " חרפה נצחית, אות קין."));
        phrases.add(new Phrase("דרג ", " שלב, דרגה."));
        phrases.add(new Phrase("דרגנוע ", " מדרגות נעות."));
        phrases.add(new Phrase("דרגש ", " כיסא נמוך, הדום, שרפרף."));
        phrases.add(new Phrase("דרדרסים ", " נעלי בית, אנפילאות."));
        phrases.add(new Phrase("דרדק ", " ילד, זאטוט, ינוקא, עולל."));
        phrases.add(new Phrase("דרדר ", " סוג של קוץ, חרול, חוח."));
        phrases.add(new Phrase("דריכות", "מתיחות."));
        phrases.add(new Phrase("דריסת רגל ", " עמדה, מאחז."));
        phrases.add(new Phrase("דרך ", " מתח."));
        phrases.add(new Phrase("דרך ארץ ", " נימוסים, התנהגות נאותה."));
        phrases.add(new Phrase("דרך הישר ", " התנהגות טובה ונאה."));
        phrases.add(new Phrase("דרך המלך ", " הדרך הראשית."));
        phrases.add(new Phrase("דרך חתחתים ", " דרך לא סלולה, מלאה במכשולים."));
        phrases.add(new Phrase("דרך כוכבו ", " הצליח."));
        phrases.add(new Phrase("דרסטי ", " תקיף, נמרץ, קיצוני."));
        phrases.add(new Phrase("דרקוני ", " קשה ביותר."));
        phrases.add(new Phrase("דרש ", " פירש, ביאר."));
        phrases.add(new Phrase("דרשה ", " הרצאה שעיקרה פרשנות של טקסט."));
        phrases.add(new Phrase("דש ", " 1. רמס, דרס; 2. קפל בבגד."));
        phrases.add(new Phrase("דשדש ", " צעד במקום, בוסס, הידס, דידה."));
        phrases.add(new Phrase("דשן ", " שמן, שופע."));
        phrases.add(new Phrase("הא בהא תליא ", " הדברים תלויים זה בזה."));
        phrases.add(new Phrase("האביס ", " האכיל, הלעיט, פיטם."));
        phrases.add(new Phrase("האדיר ", " שיבח, הילל, קילס."));
        phrases.add(new Phrase("האיר פנים ", " גילה רצון טוב, הסביר פנים."));
        phrases.add(new Phrase("האמיר ", " גדל, התייקר."));
        phrases.add(new Phrase("האנשה ", " ייחוס תכונות אנושיות לבעלי חיים."));
        phrases.add(new Phrase("האפיל ", " החשיך."));
        phrases.add(new Phrase("האצלה ", " העברה, השראה."));
        phrases.add(new Phrase("האריך אפו ", " התאפק מלכעוס."));
        phrases.add(new Phrase("הארקה ", " חיבור מכשיר חשמלי לאדמה למניעת התחשמלות."));
        phrases.add(new Phrase("הב! ", " תן!"));
        phrases.add(new Phrase("הבאי ", " הגזמה, הבל, להג, קש וגבבה."));
        phrases.add(new Phrase("הבאיש ", " הפיץ ריח רע."));
        phrases.add(new Phrase("הבאיש את ריחו ", " הוציא לו שם רע."));
        phrases.add(new Phrase("רכיב ", " חלק, מרכיב."));
        phrases.add(new Phrase("רכיכה ", " בעל חיים חסר חוליות."));
        phrases.add(new Phrase("רכינה ", " התכופפות, גהירה, גחינה."));
        phrases.add(new Phrase("רכס ", " כיפתר, כיבן."));
        phrases.add(new Phrase("רם דרג ", " רם מעלה, חשוב, נכבד."));
        phrases.add(new Phrase("רמה קרנו ", " זכה להערכה ולכבוד."));
        phrases.add(new Phrase("רמץ ", " אפר חם, שיירי גחלים."));
        phrases.add(new Phrase("רמש ", " שם כולל לחרקים וזוחלים."));
        phrases.add(new Phrase("רנדומלי ", " אקראי, שרירותי."));
        phrases.add(new Phrase("רנטבילי ", " רווחי, משתלם."));
        phrases.add(new Phrase("רסיטל ", " קונצרט של אמן אחד."));
        phrases.add(new Phrase("רע ", " חבר, ידיד, עמית."));
        phrases.add(new Phrase("רעבתן ", " זללן, גרגרן."));
        phrases.add(new Phrase("רעה בשדות זרים ", " פנה לתרבות שונה או לאמונה אחרת."));
        phrases.add(new Phrase("רעה חולה ", " צרה גדולה."));
        phrases.add(new Phrase("רעלה ", " צעיף לכיסוי הפנים."));
        phrases.add(new Phrase("רעץ ", " שבר, פוצץ, רצץ."));
        phrases.add(new Phrase("רף ", " מדף, איצטבה, נדבך, קורה."));
        phrases.add(new Phrase("רפה ", " נחלש, כהה."));
        phrases.add(new Phrase("רפה שכל ", " מוגבל בשכלו."));
        phrases.add(new Phrase("רפורמה ", " תיקון יסודי, שידוד מערכות."));
        phrases.add(new Phrase("רפיון רוח ", " חולשה."));
        phrases.add(new Phrase("רפרזנטטיבי ", " ייצוגי."));
        phrases.add(new Phrase("רפרף ", " ריחף."));
        phrases.add(new Phrase("רפרפת ", " פודינג, חביצה."));
        phrases.add(new Phrase("רפש ", " בוץ, לכלוך, דומן, סחי."));
        phrases.add(new Phrase("רץ ", " שליח מהיר, בלדר, מלאך, ציר."));
        phrases.add(new Phrase("רצען ", " 1. סנדלר; 2. אומן העובד בעור."));
        phrases.add(new Phrase("רצץ ", " שבר, ניפץ, רעץ."));
        phrases.add(new Phrase("רקבובית ", " חומר אורגני שהרקיב."));
        phrases.add(new Phrase("רקויאם ", " שיר אבל, שיר אשכבה."));
        phrases.add(new Phrase("רקח ", " ערבב."));
        phrases.add(new Phrase("רקיע ", " שמים."));
        phrases.add(new Phrase("רקיעה ", " דריכה בכוח."));
        phrases.add(new Phrase("רקיק ", " עוגה, אפיפית, צפיחית, פכסם."));
        phrases.add(new Phrase("רקק ", " ביצה, מקווה מים עכורים."));
        phrases.add(new Phrase("רקק ", " ירק."));
        phrases.add(new Phrase("רש ", " עני, דלפון, דל, אביון."));
        phrases.add(new Phrase("רשות הרבים ", " מקום ציבורי."));
        phrases.add(new Phrase("רשף ", " גחלת, ניצוץ, שביב."));
        phrases.add(new Phrase("רתת ", " רעד, רטט."));
        phrases.add(new Phrase("רתתן ", " הססן."));
        phrases.add(new Phrase("שאה ", " נחרב."));
        phrases.add(new Phrase("שאול ", " גיהינום, תופת."));
        phrases.add(new Phrase("שאון ", " רעש, המולה."));
        phrases.add(new Phrase("שאור שבעיסה ", " החלק העיקרי."));
        phrases.add(new Phrase("שאט ", " בוז, תיעוב, סלידה."));
        phrases.add(new Phrase("שאיה ", " חורבן, הרס."));
        phrases.add(new Phrase("שאר בשר ", " קרוב משפחה."));
        phrases.add(new Phrase("שאר רוח ", " עומק מחשבה מעבר לעניינים יומיומיים."));
        phrases.add(new Phrase("שבב ", " רסיס, נתז, שבריר, פלח."));
        phrases.add(new Phrase("שבט ", " מקל, מטה, שוט, פרגול, מגלב."));
        phrases.add(new Phrase("שביב ", " ניצוץ, רשף, קרן אור."));
        phrases.add(new Phrase("שביל הזהב ", " דרך ממוצעת."));
        phrases.add(new Phrase("שביל הנחש ", " דרך עקלקלה."));
        phrases.add(new Phrase("שביס ", " כיסוי ראש."));
        phrases.add(new Phrase("שבלוני ", " שגרתי, מוכר, חסר ייחוד."));
        phrases.add(new Phrase("שבע ימים ", " קשיש."));
        phrases.add(new Phrase("שבעה מדורי גיהינום ", " ייסורים קשים."));
        phrases.add(new Phrase("שבק ", " עזב, נטש."));
        phrases.add(new Phrase("שבק חיים לכל חי ", " מת, בר מינן."));
        phrases.add(new Phrase("שבריה ", " חרב קצרה, פגיון, סיף, שלח."));
        phrases.add(new Phrase("שבריר ", " פלח, רסיס, שבב, נתז."));
        phrases.add(new Phrase("שגגה ", " טעות, שגיאה, משוגה."));
        phrases.add(new Phrase("שגור ", " רגיל."));
        phrases.add(new Phrase("שגיא ", " עצום, כביר, נשגב, שגיב."));
        phrases.add(new Phrase("שדוף ", " מיובש, נבוב, צפוד, חסר תוכן."));
        phrases.add(new Phrase("שדמה ", " שדה תבואה או כרם."));
        phrases.add(new Phrase("שה תמים ", " כינוי לאדם הנראה תמים רק למראית עין."));
        phrases.add(new Phrase("שובה ", " מתינות, נחת."));
        phrases.add(new Phrase("שובה לב ", " גורם לרגשות חיבה כלפיו."));
        phrases.add(new Phrase("שוביניזם ", " התנגדות לשוויון זכויות לנשים."));
        phrases.add(new Phrase("שובל ", " 1. שוליים; 2. עקבות במים או באוויר."));
        phrases.add(new Phrase("שווה בנפשך ", " תאר לעצמך."));
        phrases.add(new Phrase("שווה לכל נפש ", " מיועד ומתאים לכל אחד."));
        phrases.add(new Phrase("שווה נפש ", " אדיש."));
        phrases.add(new Phrase("שוזף עינו ", " מביט."));
        phrases.add(new Phrase("שוחה ", " בור, מהמורה, פוקה, דחי, פח."));
        phrases.add(new Phrase("שוחר ", " חובב."));
        phrases.add(new Phrase("שומה ", " 1. הערכה, אומדן; 2. בליטה בעור."));
        phrases.add(new Phrase("שומה עליו ", " חובה עליו, צריך."));
        phrases.add(new Phrase("שוע ", " עשיר, אריסטוקרט."));
        phrases.add(new Phrase("שועה ", " זעקה, קריאה לעזרה."));
        phrases.add(new Phrase("שועט ", " דוהר."));
        phrases.add(new Phrase("שופי ", " נחת."));
        phrases.add(new Phrase("שופרא דשופרא ", " מיטב, מובחר."));
        phrases.add(new Phrase("שוקק חיים ", " מלא אנשים ופעילות."));
        phrases.add(new Phrase("שוקת ", " כלי עמוק להשקיית בהמות."));
        phrases.add(new Phrase("שור! ", " ראה, הבט, הסתכל."));
        phrases.add(new Phrase("שורר ", " קיים, מאפיין מקום או מצב."));
        phrases.add(new Phrase("שושבין ", " חבר, בן לוויה, סנדק."));
        phrases.add(new Phrase("שזר ", " שילב."));
        phrases.add(new Phrase("שח ", " התכופף, רכן, גחן, גהר, שחה."));
        phrases.add(new Phrase("שחוח ", " כפוף."));
        phrases.add(new Phrase("שחון ", " חם ויבש."));
        phrases.add(new Phrase("שחור על גבי לבן ", " מפורש."));
        phrases.add(new Phrase("שחל ", " אריה, כפיר, לביא, ליש."));
        phrases.add(new Phrase("שחץ ", " גאווה, יהירות, התפארות."));
        phrases.add(new Phrase("שחק ", " שמיים."));
        phrases.add(new Phrase("שחרית ", " 1. שעת בוקר; 2. תפילת בוקר."));
        phrases.add(new Phrase("שטח ", " פרס."));
        phrases.add(new Phrase("שטח בקשתו בפניו ", " ביקש מאוד, התחנן, חילה את פניו."));
        phrases.add(new Phrase("שטם ", " שנא, צרר."));
        phrases.add(new Phrase("שטנה ", " דברי גנאי, לעז, עלילה."));
        phrases.add(new Phrase("שיבוט ", " 1. חביטה, רידוד; 2. שכפול גנטי."));
        phrases.add(new Phrase("שיג ושיח ", " משא ומתן, שקלא וטריא."));
        phrases.add(new Phrase("שיגיון ", " הרהור, שרעף, עשתון, הגיג."));
        phrases.add(new Phrase("שידד ", " פורר את הקרקע, תיחח."));
        phrases.add(new Phrase("שידה ", " ארון נמוך."));
        phrases.add(new Phrase("שידוד מערכות ", " תיקון דברים מהיסוד."));
        phrases.add(new Phrase("שיהוי", "עיכוב, איחור, דיחוי."));
        phrases.add(new Phrase("שיווה ", " דימה, תיאר, הציג."));
        phrases.add(new Phrase("שיווה בנפשו ", " תיאר לעצמו, שיער."));
        phrases.add(new Phrase("שיחת זמנו לריק ", " בזבז זמן."));
        phrases.add(new Phrase("שיכוך ", " הרגעה."));
        phrases.add(new Phrase("שיכול ", " הצלבה, החלפה, היפוך."));
        phrases.add(new Phrase("שיכול רגלים ", " שילוב רגליים, הנחת רגל על רגל."));
        phrases.add(new Phrase("שימצה ", " חרפה, גנאי."));
        phrases.add(new Phrase("שינס ", " חגר, אזר."));
        phrases.add(new Phrase("שיסה ", " הסית, יצר פרובוקציה."));
        phrases.add(new Phrase("שיסע ", " קרע, ביתק, ביתר, פילח."));
        phrases.add(new Phrase("שיסף ", " חתך, שיסע, פילח, ריטש."));
        phrases.add(new Phrase("שיעור ", " מידה, כמות, גודל."));
        phrases.add(new Phrase("שיפול ", " תחתית, החלק הנמוך בדבר."));
        phrases.add(new Phrase("שיפון ", " סוג של דגן."));
        phrases.add(new Phrase("שיקוץ ", " תועבה, דבר מאוס, פיגול."));
        phrases.add(new Phrase("שירבוט ", " רישום סימנים ללא משמעות, קשקוש."));
        phrases.add(new Phrase("שירות דב ", " כוונה טובה עם תוצאות מזיקות."));
        phrases.add(new Phrase("שירש ", " עקר מהשורש."));
        phrases.add(new Phrase("שירת הברבור ", " פעולה מהוללת אחרונה לפני פרישה."));
        phrases.add(new Phrase("שית ", " יסוד, בסיס, אושיה."));
        phrases.add(new Phrase("שכב ", " האבן התחתונה בריחיים."));
        phrases.add(new Phrase("שכוי", "תרנגול, גבר."));
        phrases.add(new Phrase("שכיב מרע ", " גוסס, חולה אנוש."));
        phrases.add(new Phrase("שכיה ", " קישוט."));
        phrases.add(new Phrase("שכיח", "מצוי, רגיל, נפוץ."));
        phrases.add(new Phrase("שכך ", " נח, שקט, נרגע."));
        phrases.add(new Phrase("שכלתן ", " רציונליסט, מי שמעדיף שכל על רגש."));
        phrases.add(new Phrase("שכם אחד ", " בכוחות משותפים."));
        phrases.add(new Phrase("שכתוב ", " כתיבה מחדש."));
        phrases.add(new Phrase("שלג דאשתקד ", " דבר שעבר ואינו מעניין עוד, עפרא דארעא, כקליפת השום."));
        phrases.add(new Phrase("שלה ", " הוציא מהמים, משה."));
        phrases.add(new Phrase("שלהי ", " סוף."));
        phrases.add(new Phrase("שלווה סטואית ", " שלווה מושלמת."));
        phrases.add(new Phrase("שלח ", " חרב קצרה, פגיון, שבריה, סיף."));
        phrases.add(new Phrase("שלח ידו ", " 1. לקח לעצמו, גנב; 2. עסק ב…"));
        phrases.add(new Phrase("שלחופה ", " צב."));
        phrases.add(new Phrase("שליש ", " קצין האחראי על פעילות מנהלתית."));
        phrases.add(new Phrase("שלמה ", " שמלה, בגד רחב."));
        phrases.add(new Phrase("שלמונים ", " שוחד, בצע."));
        phrases.add(new Phrase("שלף ", " שדה שנקצר ועוד לא נחרש."));
        phrases.add(new Phrase("שלק ", " הרתיח במים, בישל, חלט, שפת."));
        phrases.add(new Phrase("שם דבר ", " מפורסם, שיצא שמו."));
        phrases.add(new Phrase("שם לאל ", " הכשיל, סיכל, ביטל."));
        phrases.add(new Phrase("שם נפשו בכפו ", " הסתכן."));
        phrases.add(new Phrase("שם פעמיו ", " יצא לדרך, הלך לעבר."));
        phrases.add(new Phrase("שמורה ", " עפעף."));
        phrases.add(new Phrase("שמיטה ", " עזיבה, ויתור, נטישה."));
        phrases.add(new Phrase("שמיר ", " אבן קשה וחזקה."));
        phrases.add(new Phrase("שמיר ושית ", " שממה, עזובה, ישימון."));
        phrases.add(new Phrase("שמנה וסלתה ", " עילית."));
        phrases.add(new Phrase("שמץ ", " מעט, קורט, קורטוב, קמצוץ."));
        phrases.add(new Phrase("שנה ", " לימד, שינן."));
        phrases.add(new Phrase("שני ", " אדום, ארגמן, סיקרה, חכלילי."));
        phrases.add(new Phrase("שניוני ", " ממדרגה שניה."));
        phrases.add(new Phrase("שנף ", " וניל."));
        phrases.add(new Phrase("שנץ ", " סרט, שרוך."));
        phrases.add(new Phrase("שעבוד ", " עבדות, כיבוש."));
        phrases.add(new Phrase("שעה ", " שם לב, נענה, הקשיב."));
        phrases.add(new Phrase("(גם) שעון מקולקל מראה את השעה הנכונה פעמיים ביום ", " כל אדם, לא יוצלח ככל שיהיה, עשוי להצליח מדי פעם."));
        phrases.add(new Phrase("שעטה ", " דפיקה בקרקע ברגל, דהרה."));
        phrases.add(new Phrase("שעטנז ", " ערבוב מין בשאינו מינו."));
        phrases.add(new Phrase("שעיר ", " תיש, צפיר."));
        phrases.add(new Phrase("שעיר לעזאזל ", " כינוי למי שנושא בעונש עבור כולם."));
        phrases.add(new Phrase("שעל ", " צעד, פעם, פסע."));
        phrases.add(new Phrase("שערוך ", " הערכה מחדש."));
        phrases.add(new Phrase("שפאים ", " שבבים העפים בשיוף עץ."));
        phrases.add(new Phrase("שפוף ", " כפוף, גחון, שחוח, רכון."));
        phrases.add(new Phrase("שפחה ", " משרתת, אמה."));
        phrases.add(new Phrase("שפיר ", " יפה, נאה, ניחא."));
        phrases.add(new Phrase("שפך על פניו קיתונות של בוז ", " העליב, השמיץ, גידף, חירף, גינה, ניאץ, קילס."));
        phrases.add(new Phrase("שפל המדרגה ", " מצב ירוד."));
        phrases.add(new Phrase("שפרה ", " יופי, חן."));
        phrases.add(new Phrase("שפת ", " שם על האש, שלק, חלט."));
        phrases.add(new Phrase("שצף ", " זרם חזק, שטף."));
        phrases.add(new Phrase("שקיקה ", " תשוקה, להיטות, כמיהה."));
        phrases.add(new Phrase("שקלא וטריא ", " משא ומתן, שיח ושיג."));
        phrases.add(new Phrase("שקעה שמשו ", " ירד מגדולתו."));
        phrases.add(new Phrase("שרג ", " קלע, סיבך, שילב."));
        phrases.add(new Phrase("שרות דב ", " שרות בעל תוצאות לוואי שליליות."));
        phrases.add(new Phrase("שריג ", " ענף, בד, זרד, זלזל, נצר, זמורה."));
        phrases.add(new Phrase("שרך דרכיו ", " סר מדרך הישר."));
        phrases.add(new Phrase("שרלטן ", " נוכל, מתחזה, נכלולי."));
        phrases.add(new Phrase("שרעפים ", " מחשבות, הרהורים, עשתונות."));
        phrases.add(new Phrase("שרף ", " מלאך, כרוב, אראל."));
        phrases.add(new Phrase("שררה ", " שלטון, ממשל, אדנות, מרות."));
        phrases.add(new Phrase("שש ", " שמח, עלז, עלץ, דץ, רן."));
        phrases.add(new Phrase("שת ", " שם, הניח."));
        phrases.add(new Phrase("שתום עין ", " עיוור בעין אחת."));
        phrases.add(new Phrase("שתת ", " נזל, זלג, ניגר."));
        phrases.add(new Phrase("תאב ", " רוצה, משתוקק, כמה, מתאווה."));
        phrases.add(new Phrase("תאוטה ", " האטת המהירות."));
        phrases.add(new Phrase("תאניה ", " בכי."));
        phrases.add(new Phrase("תבל", "עולם, יקום, חלד, קוסמוס."));
        phrases.add(new Phrase("תברוגת ", " מערכת החריצים בברגים ואומים  גם “תבריג” ."));
        phrases.add(new Phrase("תגר ", " סוחר, רוכל, תגרן."));
        phrases.add(new Phrase("תגרן ", " 1. סוחר קטן, רוכל; 2. מי שמרבה להתווכח."));
        phrases.add(new Phrase("תדיר ", " לעיתים קרובות, תכוף."));
        phrases.add(new Phrase("תהה על קנקנו ", " בחן, בדק, עמד על טיבו."));
        phrases.add(new Phrase("תהום הנשיה ", " שכחה מוחלטת."));
        phrases.add(new Phrase("תו לא ", " זהו זה."));
        phrases.add(new Phrase("תואי ", " מסלול, ציר, נתיב."));
        phrases.add(new Phrase("תואנה ", " אשמת שקר, עלילה."));
        phrases.add(new Phrase("תוגה ", " עצב, יגון, דכדוך, דאבה."));
        phrases.add(new Phrase("תוהו ", " שממה, ישימון, בתה, ציה."));
        phrases.add(new Phrase("תוחלת ", " תקווה, ציפיה, יהב."));
        phrases.add(new Phrase("תוכו כברו ", " ישר, אמיתי, כן."));
        phrases.add(new Phrase("תוכחה ", " נזיפה, הטפת מוסר."));
        phrases.add(new Phrase("תוכן ", " אסטרונום."));
        phrases.add(new Phrase("תולדה ", " תוצאה, מסקנה, פועל יוצא."));
        phrases.add(new Phrase("תולה את יהבו ", " מקווה."));
        phrases.add(new Phrase("תופין ", " עוגה, אפיפית, רקיק, פכסם."));
        phrases.add(new Phrase("תופעות טקטוניות ", " תופעות בקליפת כדור הארץ."));
        phrases.add(new Phrase("תופת ", " 1. גיהינום, שאול; 2. מוקד, שריפה גדולה."));
        phrases.add(new Phrase("תור ", " תקופה, עידן."));
        phrases.add(new Phrase("תור הזהב ", " תקופה מוצלחת, ימי זוהר."));
        phrases.add(new Phrase("תורפה ", " חולשה, רפיון."));
        phrases.add(new Phrase("תושיה ", " עצה, חוכמה, כושר המצאה."));
        phrases.add(new Phrase("תזה ", " הנחת יסוד, אקסיומה."));
        phrases.add(new Phrase("תזזית ", " טירוף, שיגעון, דיבוק, אמוק."));
        phrases.add(new Phrase("תחוח ", " רך."));
        phrases.add(new Phrase("תחולה ", " מועד ההתחלה."));
        phrases.add(new Phrase("תחום ", " מגודר, מוגבל."));
        phrases.add(new Phrase("תחח ", " פורר."));
        phrases.add(new Phrase("תחיבה ", " נעיצה, תקיעה, הכנסת דבר לתוך דבר."));
        phrases.add(new Phrase("תחינה ", " תפילה, בקשת רחמים, עתירה."));
        phrases.add(new Phrase("תחלואה ", " מחלה."));
        phrases.add(new Phrase("תחליב ", " תערובת נוזלים, אמולסיה."));
        phrases.add(new Phrase("תחריט ", " ציור חקוק במתכת."));
        phrases.add(new Phrase("תיאולוגיה ", " חקר האלוהות."));
        phrases.add(new Phrase("תיאוקרטיה ", " שלטון שאנשי דת עומדים בראשו."));
        phrases.add(new Phrase("תיבת פנדורה ", " פרשה הטומנת בחובה צרות."));
        phrases.add(new Phrase("תיגר ", " ריב, תגרה, קטטה."));
        phrases.add(new Phrase("תיכון ", " אמצעי, נמצא בתווך."));
        phrases.add(new Phrase("תימרות עשן ", " עמודי עשן העולים משריפה."));
        phrases.add(new Phrase("תינה ", " 1. סיפר, תיאר; 2. קונן, ספד."));
        phrases.add(new Phrase("תינה אהבים ", " התעלס, התלטף."));
        phrases.add(new Phrase("תיעב ", " סלד, מאס, קצה נפשו, בחל."));
        phrases.add(new Phrase("תיעול ", " הפניה לאפיקים הרצויים."));
        phrases.add(new Phrase("תיקן ", " מקק, ג’וק."));
        phrases.add(new Phrase("תירוש ", " יין חדש, מיץ ענבים אשר איננו משכר  ראה גם “נקטר” ו”עסיס” ."));
        phrases.add(new Phrase("תיתורה ", " שוליים, סרח."));
        phrases.add(new Phrase("תכונה ", " פעילות, התכוננות."));
        phrases.add(new Phrase("תככים ", " מזימות, סכסכנות."));
        phrases.add(new Phrase("תכלית ", " מטרה."));
        phrases.add(new Phrase("תכריכים ", " בדים העוטפים את גופת המת."));
        phrases.add(new Phrase("תכתיב ", " כפייה לפעול בצורה מסויימת."));
        phrases.add(new Phrase("תל ", " גבעה מלאכותית, גל, ערמה."));
        phrases.add(new Phrase("תלאות ", " צרות, ייסורים, תלאובות."));
        phrases.add(new Phrase("תלה את הקולר בצווארו ", " האשים."));
        phrases.add(new Phrase("תלה עצמו באילן גדול ", " הסתמך בדבריו על גדולים ממנו."));
        phrases.add(new Phrase("תלוי ועומד ", " ממתין להכרעה, מוטל בספק."));
        phrases.add(new Phrase("תלוי על בלימה ", " ללא בסיס."));
        phrases.add(new Phrase("תלי ", " 1. קולב לתליית בדים; 2. אשפה, תיק לחיצים."));
        phrases.add(new Phrase("תלם ", " חריץ שהמחרשה עושה באדמה, מענית."));
        phrases.add(new Phrase("תם ", " תמים, נאיבי, שלם."));
        phrases.add(new Phrase("תם ", " נגמר, נשלם."));
        phrases.add(new Phrase("תמוכה ", " משענת, סמוכה."));
        phrases.add(new Phrase("תמורה ", " 1. תחליף; 2. שינוי."));
        phrases.add(new Phrase("תמחור ", " קביעת מחירו של מוצר או שירות."));
        phrases.add(new Phrase("תמימות דעים ", " הסכמה, קונצנזוס."));
        phrases.add(new Phrase("תמיר ", " גבוה, זקוף, רם קומה."));
        phrases.add(new Phrase("תמלוגים ", " תשלומים הניתנים לבעלי זכויות לאורך זמן."));
        phrases.add(new Phrase("תמליל ", " טקסט ערוך, גרסה סופית של הטקסט."));
        phrases.add(new Phrase("תמסח ", " תנין, קרוקודיל."));
        phrases.add(new Phrase("תמרור ", " צער, יגון, דכדוך, תוגה, דאבה."));
        phrases.add(new Phrase("תנובה ", " יבול, פרי, תוצרת חקלאית."));
        phrases.add(new Phrase("תסכית רדיו ", " מחזה המשודר ברדיו."));
        phrases.add(new Phrase("תסמין ", " סימן היכר, סימפטום."));
        phrases.add(new Phrase(")גם) תרנגול עיוור מוצא לעיתים גרגר ", " המזל מאיר גם לחסרי היכולת מדי פעם."));
        phrases.add(new Phrase("תעה ", " חיפש את הדרך, סטה מדרך הישר."));
        phrases.add(new Phrase("תעודת עניות ", " מעשה המעיד על אוזלת יד ראויה לגנאי."));
        phrases.add(new Phrase("תעוקה ", " לחץ, מצוקה, מועקה."));
        phrases.add(new Phrase("תענית ", " צום."));
        phrases.add(new Phrase("תעצומה ", " כוח, עוצמה, חוסן, עזוז."));
        phrases.add(new Phrase("תעצומות נפש ", " כוחות נפש, חוסן מנטלי."));
        phrases.add(new Phrase("תער ", " סכין גילוח."));
        phrases.add(new Phrase("תעתוע ", " 1. בלבול, טירוף; 2. הטעיה."));
        phrases.add(new Phrase(")ה)תפוח לא נופל רחוק מהעץ ", " לצאצא מכנה משותף גדול עם הוריו או משפחתו."));
        phrases.add(new Phrase("תפוח רקוב ", " סטה מדרך הישר, איננו נוהג כשורה."));
        phrases.add(new Phrase("תפוקה ", " תוצאת הייצור, יבול, תוצרת."));
        phrases.add(new Phrase("תפל ", " חסר טעם."));
        phrases.add(new Phrase("תפס את השור בקרניו ", " ניגש ישר לעניין, נכנס בעובי הקורה."));
        phrases.add(new Phrase("תקיעת כף ", " הבטחה, התחייבות."));
        phrases.add(new Phrase("תקע טריז ", " הפריד."));
        phrases.add(new Phrase("תקע יתד ", " התיישב, התנחל, השתקע."));
        phrases.add(new Phrase("תקרובת ", " כיבוד, פרפראות, מגדנות."));
        phrases.add(new Phrase("תר ", " סייר, חיפש, ריגל, חקר."));
        phrases.add(new Phrase("תר אחר לבבו ", " הלך אחרי יצרו."));
        phrases.add(new Phrase("תרבית ", " מושבה של חיידקים שגודלו מלאכותית."));
        phrases.add(new Phrase("תרגימא ", " קינוח, דברי מתיקה, מגדנות."));
        phrases.add(new Phrase("תרווד ", " כף לבחישה."));
        phrases.add(new Phrase("תרומי ", " נעלה, מובחר."));
        phrases.add(new Phrase("תרחיש ", " תסריט, תיאור התרחשות אפשרית."));
        phrases.add(new Phrase("תרי עשר ", " שנים עשר, תריסר."));
        phrases.add(new Phrase("תרעומת ", " כעס, תלונה, טענה, טרוניה."));
        phrases.add(new Phrase("תרפיה ", " טיפול."));
        phrases.add(new Phrase("תרשיש ", " 1. אחת מאבני החושן; 2. נכבד, חשוב."));
        phrases.add(new Phrase("תרתי דסתרי ", " שני הדברים סותרים זה את זה."));
        phrases.add(new Phrase("תרתי משמע ", " שני מובנים לדבר."));
        phrases.add(new Phrase("תש ", " נחלש, עייף, רפה, הדלדל."));
        phrases.add(new Phrase("תשואה ", " רווח מהשקעה."));
        phrases.add(new Phrase("תשובה ניצחת", "תשובה מכרעת, סופית."));
        phrases.add(new Phrase("תשומה ", " כסף ומשאבים המושקעים בדבר."));
        phrases.add(new Phrase("תשורה ", " מתנה, שי, דורון, מנחה, תשר."));
        phrases.add(new Phrase("תשחורת ", " נוער, נעורים, עלומים."));
        phrases.add(new Phrase("תשליל ", " סרט צילום, נגטיב."));
        phrases.add(new Phrase("תשקיף ", " דו”ח הנותן תחזית."));
        phrases.add(new Phrase("תשר ", " טיפ, מתנה, תשורה, דורון, שי."));
        phrases.add(new Phrase("תשתית ", " יסוד, בסיס, מסד, כן."));
        phrases.add(new Phrase("תתרן ", " חסר חוש ריח."));

    }


    @Override
    public ArrayList<Phrase> getPhrases() {
        return phrases;
    }

    @Override
    public int getScore(String SharedPreferenceName, Context context) {
        SharedPreferences sharedPreferences = context.getSharedPreferences(SharedPreferenceName, Context.MODE_PRIVATE);
        return sharedPreferences.getInt("score", 0);
    }

    @Override
    public void saveScore(String SharedPreferenceName, int score, Context context) {
        SharedPreferences sharedPreferences = context.getSharedPreferences(SharedPreferenceName, Context.MODE_PRIVATE);
        SharedPreferences.Editor editor = sharedPreferences.edit();
        editor.putInt("score", score);
        editor.apply();
    }
}
